--
-- PostgreSQL database dump
--

\restrict inzkDak6p9JowMdIULhRSfhoZavj9aCCHdfX23DHYAcmphbooET1EZ61cguseYh

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: asset_snapshot; Type: TABLE; Schema: public; Owner: assets
--

CREATE TABLE public.asset_snapshot (
    id bigint NOT NULL,
    estimated_annual_dividend numeric(20,2),
    notes character varying(500),
    realized_gain numeric(20,2),
    snapshot_date date NOT NULL,
    total_assets numeric(20,2),
    total_deposit numeric(20,2),
    total_fund_cost numeric(20,2),
    total_fund_value numeric(20,2),
    total_stock_cost numeric(20,2),
    total_stock_value numeric(20,2),
    usd_exchange_rate numeric(10,4)
);


ALTER TABLE public.asset_snapshot OWNER TO assets;

--
-- Name: asset_snapshot_id_seq; Type: SEQUENCE; Schema: public; Owner: assets
--

ALTER TABLE public.asset_snapshot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asset_snapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bank_deposit; Type: TABLE; Schema: public; Owner: assets
--

CREATE TABLE public.bank_deposit (
    id bigint NOT NULL,
    amount numeric(20,2) NOT NULL,
    bank_name character varying(30) NOT NULL,
    currency character varying(3),
    deposit_type character varying(30) NOT NULL,
    notes character varying(200),
    original_amount numeric(20,4),
    snapshot_id bigint NOT NULL,
    CONSTRAINT bank_deposit_bank_name_check CHECK (((bank_name)::text = ANY (ARRAY[('富邦'::character varying)::text, ('國泰世華'::character varying)::text, ('台新'::character varying)::text, ('華南'::character varying)::text, ('LINE_BANK'::character varying)::text, ('元大'::character varying)::text, ('永豐'::character varying)::text]))),
    CONSTRAINT bank_deposit_deposit_type_check CHECK (((deposit_type)::text = ANY (ARRAY[('活存'::character varying)::text, ('定存'::character varying)::text, ('美元活存'::character varying)::text, ('美元定存'::character varying)::text, ('證券戶'::character varying)::text, ('信用卡待付款'::character varying)::text])))
);


ALTER TABLE public.bank_deposit OWNER TO assets;

--
-- Name: bank_deposit_id_seq; Type: SEQUENCE; Schema: public; Owner: assets
--

ALTER TABLE public.bank_deposit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_deposit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fund_holding; Type: TABLE; Schema: public; Owner: assets
--

CREATE TABLE public.fund_holding (
    id bigint NOT NULL,
    bank character varying(30),
    current_value numeric(20,2) NOT NULL,
    fund_code character varying(20),
    fund_name character varying(100) NOT NULL,
    investment_amount numeric(20,2) NOT NULL,
    snapshot_id bigint NOT NULL,
    CONSTRAINT fund_holding_bank_check CHECK (((bank)::text = ANY (ARRAY[('富邦'::character varying)::text, ('國泰世華'::character varying)::text, ('台新'::character varying)::text, ('華南'::character varying)::text, ('LINE_BANK'::character varying)::text, ('元大'::character varying)::text, ('永豐'::character varying)::text])))
);


ALTER TABLE public.fund_holding OWNER TO assets;

--
-- Name: fund_holding_id_seq; Type: SEQUENCE; Schema: public; Owner: assets
--

ALTER TABLE public.fund_holding ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fund_holding_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: realized_gain; Type: TABLE; Schema: public; Owner: assets
--

CREATE TABLE public.realized_gain (
    id bigint NOT NULL,
    asset_code character varying(20),
    asset_name character varying(50) NOT NULL,
    investment_cost numeric(20,2) NOT NULL,
    market character varying(20),
    proceeds numeric(20,2) NOT NULL,
    profit numeric(20,2) NOT NULL,
    profit_rate numeric(10,6),
    sale_price numeric(15,4),
    shares numeric(15,5),
    trade_date date NOT NULL,
    trade_year integer NOT NULL,
    CONSTRAINT realized_gain_market_check CHECK (((market)::text = ANY (ARRAY[('台股'::character varying)::text, ('美股'::character varying)::text])))
);


ALTER TABLE public.realized_gain OWNER TO assets;

--
-- Name: realized_gain_id_seq; Type: SEQUENCE; Schema: public; Owner: assets
--

ALTER TABLE public.realized_gain ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.realized_gain_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_holding; Type: TABLE; Schema: public; Owner: assets
--

CREATE TABLE public.stock_holding (
    id bigint NOT NULL,
    broker character varying(30),
    currency character varying(3),
    current_value numeric(20,2) NOT NULL,
    dividend_rate numeric(10,6),
    estimated_dividend numeric(20,4),
    investment_cost numeric(20,2) NOT NULL,
    market character varying(20) NOT NULL,
    original_currency_value numeric(20,4),
    shares numeric(15,5) NOT NULL,
    stock_code character varying(20) NOT NULL,
    stock_name character varying(50) NOT NULL,
    snapshot_id bigint NOT NULL,
    CONSTRAINT stock_holding_broker_check CHECK (((broker)::text = ANY (ARRAY[('富邦證券'::character varying)::text, ('國泰證券'::character varying)::text, ('元大證券'::character varying)::text, ('華南證券'::character varying)::text]))),
    CONSTRAINT stock_holding_market_check CHECK (((market)::text = ANY (ARRAY[('台股'::character varying)::text, ('美股'::character varying)::text])))
);


ALTER TABLE public.stock_holding OWNER TO assets;

--
-- Name: stock_holding_id_seq; Type: SEQUENCE; Schema: public; Owner: assets
--

ALTER TABLE public.stock_holding ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_holding_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: asset_snapshot; Type: TABLE DATA; Schema: public; Owner: assets
--

COPY public.asset_snapshot (id, estimated_annual_dividend, notes, realized_gain, snapshot_date, total_assets, total_deposit, total_fund_cost, total_fund_value, total_stock_cost, total_stock_value, usd_exchange_rate) FROM stdin;
1	0.00	\N	\N	2021-03-19	5508988.00	3630561.00	1092000.00	951417.00	683592.00	927010.00	\N
2	0.00	\N	\N	2022-04-01	6413934.00	4362822.00	882000.00	659227.00	1109450.00	1391885.00	\N
4	351320.89	\N	\N	2025-12-31	15494404.53	7721226.00	894000.00	670850.00	4213976.14	7102328.53	\N
5	0.00	\N	\N	2024-12-31	11984386.65	6116918.00	969500.00	763201.00	3502373.70	5104267.65	\N
6	0.00	\N	\N	2024-05-20	10642535.30	5720621.00	1050000.00	870173.00	3006155.62	4051741.30	\N
7	0.00	\N	\N	2023-05-19	7651757.00	3748231.00	993000.00	682951.00	3144849.64	3220575.00	\N
8	0.00	\N	\N	2020-05-20	4425479.00	2608696.00	1116000.00	933602.00	864972.10	883181.00	\N
3	0.00	\N	\N	2026-04-03	16642375.00	8344464.00	903000.00	670569.00	4391523.52	7627342.00	\N
\.


--
-- Data for Name: bank_deposit; Type: TABLE DATA; Schema: public; Owner: assets
--

COPY public.bank_deposit (id, amount, bank_name, currency, deposit_type, notes, original_amount, snapshot_id) FROM stdin;
1	174109.00	富邦	TWD	活存	\N	\N	1
2	2715000.00	富邦	TWD	定存	\N	\N	1
3	45733.00	華南	TWD	活存	\N	\N	1
4	65719.00	永豐	TWD	活存	\N	\N	1
5	630000.00	永豐	TWD	定存	\N	\N	1
6	339784.00	富邦	TWD	活存	\N	\N	2
7	3210000.00	富邦	TWD	定存	\N	\N	2
8	17126.00	華南	TWD	活存	\N	\N	2
9	559796.00	元大	TWD	活存	\N	\N	2
10	16974.00	元大	TWD	活存	\N	\N	2
11	59142.00	永豐	TWD	活存	\N	\N	2
12	160000.00	永豐	TWD	定存	\N	\N	2
27	60287.00	富邦	TWD	證券戶	\N	\N	4
28	3645000.00	富邦	TWD	定存	\N	\N	4
29	189704.00	富邦	USD	美元活存	\N	\N	4
30	-9188.00	富邦	TWD	信用卡待付款	\N	\N	4
31	580000.00	台新	TWD	定存	\N	\N	4
32	84057.00	LINE_BANK	TWD	活存	\N	\N	4
33	7707.00	華南	TWD	證券戶	\N	\N	4
34	83749.00	國泰世華	TWD	活存	\N	\N	4
35	2350000.00	國泰世華	TWD	定存	\N	\N	4
36	605540.00	國泰世華	USD	美元活存	\N	\N	4
37	-125193.00	國泰世華	TWD	信用卡待付款	\N	\N	4
38	2649.00	元大	TWD	活存	\N	\N	4
39	250000.00	元大	TWD	定存	\N	\N	4
40	-3086.00	元大	TWD	信用卡待付款	\N	\N	4
41	55562.00	富邦	TWD	證券戶	\N	\N	5
42	3775000.00	富邦	TWD	定存	\N	\N	5
43	9808.00	華南	TWD	證券戶	\N	\N	5
44	598920.00	元大	TWD	活存	\N	\N	5
45	17627.00	元大	TWD	證券戶	\N	\N	5
46	1.00	元大	TWD	活存	\N	\N	5
47	1660000.00	元大	TWD	定存	\N	\N	5
48	48147.00	富邦	TWD	證券戶	\N	\N	6
49	4505000.00	富邦	TWD	定存	\N	\N	6
50	15145.00	華南	TWD	證券戶	\N	\N	6
51	581969.00	元大	TWD	活存	\N	\N	6
52	1.00	元大	TWD	活存	\N	\N	6
53	10359.00	元大	TWD	證券戶	\N	\N	6
54	560000.00	元大	TWD	定存	\N	\N	6
55	29048.00	富邦	TWD	活存	\N	\N	7
56	2990000.00	富邦	TWD	定存	\N	\N	7
57	12349.00	華南	TWD	活存	\N	\N	7
58	537284.00	元大	TWD	活存	\N	\N	7
59	1.00	元大	TWD	活存	\N	\N	7
60	19548.00	元大	TWD	證券戶	\N	\N	7
61	1.00	永豐	TWD	活存	\N	\N	7
62	160000.00	永豐	TWD	定存	\N	\N	7
63	111937.00	富邦	TWD	活存	\N	\N	8
64	2290000.00	富邦	TWD	定存	\N	\N	8
65	47802.00	華南	TWD	活存	\N	\N	8
66	158957.00	永豐	TWD	活存	\N	\N	8
347	90597.00	富邦	TWD	證券戶	\N	\N	3
348	2925000.00	富邦	TWD	定存	\N	\N	3
349	171606.00	富邦	USD	美元活存	\N	\N	3
350	-10351.00	富邦	TWD	信用卡待付款	\N	\N	3
351	1833458.00	台新	TWD	定存	\N	\N	3
352	41896.00	LINE_BANK	TWD	活存	\N	\N	3
353	5038.00	華南	TWD	證券戶	\N	\N	3
354	54334.00	國泰世華	TWD	活存	\N	\N	3
355	2500000.00	國泰世華	TWD	定存	\N	\N	3
356	483819.00	國泰世華	USD	美元活存	\N	\N	3
357	-2567.00	國泰世華	TWD	信用卡待付款	\N	\N	3
358	3598.00	元大	TWD	活存	\N	\N	3
359	-1964.00	元大	TWD	信用卡待付款	\N	\N	3
360	250000.00	元大	TWD	定存	\N	\N	3
\.


--
-- Data for Name: fund_holding; Type: TABLE DATA; Schema: public; Owner: assets
--

COPY public.fund_holding (id, bank, current_value, fund_code, fund_name, investment_amount, snapshot_id) FROM stdin;
1	富邦	48640.00	\N	富達亞洲高收益 (月配)	57000.00	1
2	富邦	134081.00	\N	聯博美國收益基金AA級別 (月配)	150000.00	1
3	華南	123627.00	\N	聯博全球高收益債券AA-南非幣避險 (月配)	119000.00	1
4	華南	130234.00	\N	富達亞洲高收益 (月配)	186000.00	1
5	華南	32765.00	\N	施羅德歐洲股息基金美元避險A (月配)	38000.00	1
6	華南	125353.00	\N	摩根環球策略債券基金 (月配)	137000.00	1
7	華南	130191.00	\N	富達歐洲入息基金美元避險 (月配)	121000.00	1
8	華南	6302.00	\N	聯博美國成長基金 (月配)	6000.00	1
9	華南	145392.00	\N	聯博全球高收益債券AT (月配)	178000.00	1
10	華南	74832.00	\N	聯博全球高收益債券AT (月配) (單筆申購)	100000.00	1
11	富邦	33529.00	\N	富達亞洲高收益 (月配)	57000.00	2
12	華南	157561.00	\N	聯博全球高收益債券AA-南非幣避險 (月配)	167000.00	2
13	華南	108631.00	\N	富達亞洲高收益 (月配)	210000.00	2
14	華南	20671.00	\N	施羅德環球收息債券南非幣避險月配	21000.00	2
15	華南	121323.00	\N	摩根環球策略債券基金 (月配)	137000.00	2
16	華南	7044.00	\N	富達歐洲入息基金美元避險 (月配)	6000.00	2
17	華南	7048.00	\N	聯博美國成長基金 (月配)	6000.00	2
18	華南	134298.00	\N	聯博全球高收益債券AT (月配)	178000.00	2
19	華南	69122.00	\N	聯博全球高收益債券AT (月配) (單筆申購)	100000.00	2
28	華南	94825.00	\N	富達亞洲高收益 (月配)	210000.00	4
29	華南	61151.00	\N	施羅德環球收息債券南非幣避險 (月配)	60000.00	4
30	華南	123704.00	\N	聯博全球高收益債券AA-南非幣避險 (月配)	167000.00	4
31	華南	139274.00	\N	摩根環球策略債券基金 (月配)	137000.00	4
32	華南	38465.00	\N	富達歐洲入息基金美元避險 (月配)	35000.00	4
33	華南	135221.00	\N	聯博全球高收益債券AT (月配)	178000.00	4
34	華南	69597.00	\N	聯博全球高收益債券AT (月配) (單筆申購)	100000.00	4
35	元大	8613.00	\N	元大日本龍頭企業台幣累積	7000.00	4
36	華南	96127.00	\N	富達亞洲高收益 (月配)	210000.00	5
37	華南	55503.00	\N	施羅德環球收息債券南非幣避險 (月配)	60000.00	5
38	華南	118013.00	\N	聯博全球高收益債券AA-南非幣避險 (月配)	167000.00	5
39	華南	141020.00	\N	摩根環球策略債券基金 (月配)	137000.00	5
40	華南	119743.00	\N	富達歐洲入息基金美元避險 (月配)	99000.00	5
41	華南	13010.00	\N	聯博美國成長基金 (月配)	12000.00	5
42	華南	140884.00	\N	聯博全球高收益債券AT (月配)	178000.00	5
43	華南	72512.00	\N	聯博全球高收益債券AT (月配) (單筆申購)	100000.00	5
44	元大	6389.00	\N	元大日本龍頭企業台幣累積	6500.00	5
45	華南	121473.00	\N	聯博全球高收益債券AA-南非幣避險 (月配)	167000.00	6
46	華南	94513.00	\N	富達亞洲高收益 (月配)	210000.00	6
47	華南	57002.00	\N	施羅德環球收息債券南非幣避險 (月配)	60000.00	6
48	華南	136198.00	\N	摩根環球策略債券基金 (月配)	137000.00	6
49	華南	94373.00	\N	富達歐洲入息基金美元避險 (月配)	78000.00	6
50	華南	154928.00	\N	聯博美國成長基金 (月配)	117000.00	6
51	華南	137700.00	\N	聯博全球高收益債券AT (月配)	178000.00	6
52	華南	70873.00	\N	聯博全球高收益債券AT (月配) (單筆申購)	100000.00	6
53	元大	3113.00	\N	元大日本龍頭企業台幣累積	3000.00	6
54	富邦	27608.00	\N	富達亞洲高收益 (月配)	57000.00	7
55	華南	107505.00	\N	聯博全球高收益債券AA-南非幣避險 (月配)	167000.00	7
56	華南	89304.00	\N	富達亞洲高收益 (月配)	210000.00	7
57	華南	46879.00	\N	施羅德環球收息債券南非幣避險月配	57000.00	7
58	華南	126407.00	\N	摩根環球策略債券基金 (月配)	137000.00	7
59	華南	36044.00	\N	富達歐洲入息基金美元避險 (月配)	33000.00	7
60	華南	58937.00	\N	聯博美國成長基金 (月配)	54000.00	7
61	華南	125614.00	\N	聯博全球高收益債券AT (月配)	178000.00	7
62	華南	64653.00	\N	聯博全球高收益債券AT (月配) (單筆申購)	100000.00	7
63	富邦	47106.00	\N	富達亞洲高收益 (月配)	57000.00	8
64	富邦	131949.00	\N	聯博美國收益基金AA級別 (月配)	144000.00	8
65	華南	60022.00	\N	聯博全球高收益債券AA-南非幣避險 (月配)	77000.00	8
66	華南	119994.00	\N	富達亞洲高收益 (月配)	180000.00	8
67	華南	28282.00	\N	施羅德歐洲股息基金美元避險A (月配)	35000.00	8
68	華南	67612.00	\N	霸菱亞洲增長基金	68000.00	8
69	華南	127752.00	\N	摩根環球策略債券基金 (月配)	137000.00	8
70	華南	97734.00	\N	富達歐洲入息基金美元避險 (月配)	100000.00	8
71	華南	46353.00	\N	聯博美國成長基金 (月配)	40000.00	8
72	華南	136528.00	\N	聯博全球高收益債券AT (月配)	178000.00	8
73	華南	70270.00	\N	聯博全球高收益債券AT (月配) (單筆申購)	100000.00	8
234	華南	94501.00	\N	富達亞洲高收益 (月配)	210000.00	3
235	華南	59908.00	\N	施羅德環球收息債券南非幣避險 (月配)	60000.00	3
236	華南	118360.00	\N	聯博全球高收益債券AA-南非幣避險 (月配)	167000.00	3
237	華南	139712.00	\N	摩根環球策略債券基金 (月配)	137000.00	3
238	華南	46751.00	\N	富達歐洲入息基金美元避險 (月配)	44000.00	3
239	華南	133180.00	\N	聯博全球高收益債券AT (月配)	178000.00	3
240	華南	68547.00	\N	聯博全球高收益債券AT (月配) (單筆申購)	100000.00	3
241	元大	9610.00	\N	元大日本龍頭企業台幣累積	7000.00	3
\.


--
-- Data for Name: realized_gain; Type: TABLE DATA; Schema: public; Owner: assets
--

COPY public.realized_gain (id, asset_code, asset_name, investment_cost, market, proceeds, profit, profit_rate, sale_price, shares, trade_date, trade_year) FROM stdin;
1	006208	富邦台50	68510.00	台股	75717.00	7390.00	0.105200	75.9000	1000.00000	2024-01-03	2024
2	7556	意德士	97620.00	台股	112003.00	14880.00	0.147300	112.5000	1000.00000	2024-01-17	2024
3	7556	意德士	102000.00	台股	118474.00	17000.00	0.161500	119.0000	1000.00000	2024-01-18	2024
4	7556	意德士	102000.00	台股	114492.00	13000.00	0.122500	115.0000	1000.00000	2024-01-18	2024
5	7556	意德士	10200.00	台股	11849.00	1700.00	0.161700	119.0000	100.00000	2024-01-22	2024
6	7556	意德士	117667.00	台股	122456.00	5333.00	0.040700	123.0000	1000.00000	2024-01-24	2024
7	006208	富邦台50	68510.00	台股	78909.00	10590.00	0.151800	79.1000	1000.00000	2024-01-26	2024
8	0050	元大台灣50	113190.00	台股	143353.00	30510.00	0.266500	143.7000	1000.00000	2024-02-26	2024
9	2881	富邦金	54767.00	台股	67401.00	12933.00	0.230700	67.7000	1000.00000	2024-02-29	2024
10	00878	國泰永續高股息	16605.00	台股	21997.00	5445.00	0.324700	22.0500	1000.00000	2024-04-16	2024
11	006208	富邦台50	68648.00	台股	90880.00	22452.00	0.323900	91.1000	1000.00000	2024-04-16	2024
12	006208	富邦台50	68648.00	台股	90581.00	22152.00	0.319500	90.8000	1000.00000	2024-04-16	2024
13	0056	元大高股息	26139.00	台股	38298.00	12251.00	0.465200	38.3900	1000.00000	2024-04-16	2024
14	0050	元大台灣50	113190.00	台股	155074.00	42260.00	0.370000	155.4500	1000.00000	2024-04-16	2024
15	2881	富邦金	54767.00	台股	73674.00	19233.00	0.345200	74.0000	1000.00000	2024-05-15	2024
16	0056	元大高股息	25349.00	台股	40053.00	14801.00	0.580100	40.1500	1000.00000	2024-05-30	2024
17	2881	富邦金	54767.00	台股	82534.00	28133.00	0.507000	82.9000	1000.00000	2024-07-03	2024
18	00646	元大S&P500	46254.00	台股	56496.00	10346.00	0.221400	56.6000	1000.00000	2024-07-09	2024
19	00646	元大S&P500	3971.00	台股	4942.00	979.30	0.244500	56.9000	87.00000	2024-07-10	2024
20	2881	富邦金	52267.00	台股	84824.00	32933.00	0.622900	85.2000	1000.00000	2024-07-19	2024
21	7556	意德士	117667.00	台股	122955.00	5833.00	0.044900	123.5000	1000.00000	2024-08-09	2024
22	2881	富邦金	52267.00	台股	92092.00	40233.00	0.762000	92.5000	1000.00000	2024-08-06	2024
23	00850	元大台灣ESG永續	38656.00	台股	41031.00	2451.50	0.061400	47.2500	870.00000	2024-11-08	2024
24	16B3	聯博美國成長基金-AD月配級別	150000.00	台股	204139.00	54139.00	0.360900	\N	\N	2024-11-28	2024
25	2412	中華電	119169.00	台股	124946.00	5777.00	0.048500	125.5000	1000.00000	2025-02-03	2025
26	02B9	富達歐洲入息基金A股	100000.00	台股	128706.00	28706.00	0.287100	\N	\N	2025-02-17	2025
27	00882	中信中國高股息	10527.00	台股	13117.00	2590.00	0.246000	13.1500	1000.00000	2025-02-18	2025
28	AAPL	蘋果	9792.00	美股	13272.00	3480.00	0.355400	244.8600	1.65800	2025-02-18	2025
29	COIN	Coinbase	27064.00	美股	18876.00	-8188.00	-0.302500	191.3000	3.00000	2025-03-11	2025
30	MSTR	MicroStrategy	21614.00	美股	21800.00	186.00	0.008600	330.1000	2.00000	2025-03-24	2025
31	COIN	Coinbase	28270.00	美股	22014.00	-6256.00	-0.221300	165.8115	4.00000	2025-03-31	2025
32	NVDA	輝達	20374.20	美股	15839.00	-4535.20	-0.222600	95.9800	5.00000	2025-04-07	2025
33	NVDA	輝達	10188.09	美股	11014.00	825.91	0.081100	112.0000	3.00000	2025-04-09	2025
34	MSTR	MicroStrategy	26814.16	美股	26543.00	-271.16	-0.010100	269.9000	3.00000	2025-04-09	2025
35	MSTR	MicroStrategy	16566.00	美股	18342.00	1776.00	0.107200	282.6100	2.00000	2025-04-10	2025
36	NVDA	輝達	12172.05	美股	11801.00	-371.05	-0.030500	130.8000	3.00000	2025-05-13	2025
37	COIN	Coinbase	29072.34	美股	32792.00	3719.66	0.127900	277.0000	4.00000	2025-06-18	2025
38	COIN	Coinbase	25287.57	美股	36803.56	11515.99	0.455400	310.0000	4.00000	2025-06-23	2025
39	00882	中信中國高股息	10530.00	台股	13210.00	2680.00	0.254500	13.2100	1000.00000	2025-06-24	2025
40	NVDA	輝達	48898.08	美股	54057.00	5158.92	0.105500	156.3000	12.00000	2025-07-01	2025
41	COIN	Coinbase	20718.39	美股	48127.00	27408.61	1.322900	410.0000	4.00000	2025-07-17	2025
42	NVDA	輝達	51560.91	美股	63069.00	11508.09	0.223200	167.0300	12.65350	2025-07-22	2025
43	GOOGL	Alphabet Inc A	19681.00	美股	27927.00	8246.00	0.419000	228.3500	4.00000	2025-09-03	2025
44	0050	元大台灣50	29480.00	台股	63647.00	34167.00	1.159000	63.8000	1000.00000	2025-10-27	2025
45	16B3	聯博美國成長基金-AD月配級別	65000.00	台股	71570.00	6570.00	0.101100	\N	\N	2025-10-30	2025
46	AMZN	Amazon	41973.69	美股	48402.00	6428.31	0.153200	\N	6.40170	2025-11-12	2025
47	MSFT	Microsoft	93924.60	美股	106336.00	20798.00	0.221400	507.4900	6.88620	2025-11-17	2025
48	0050	元大台灣50	52030.00	台股	60000.00	7970.00	0.153200	60.2000	1000.00000	2025-11-19	2025
49	0050	元大台灣50	54020.00	台股	119200.00	65180.00	1.206600	59.6000	2000.00000	2025-11-21	2025
50	006208	富邦台50	73590.00	台股	136200.00	62610.00	0.850800	136.2000	1000.00000	2025-11-21	2025
51	006208	富邦台50	147180.00	台股	272300.00	125120.00	0.850100	136.1500	2000.00000	2025-11-21	2025
52	GOOGL	Alphabet Inc A	43500.00	美股	77771.00	34271.00	0.787800	325.6000	7.62780	2025-11-26	2025
53	006208	富邦台50	137154.00	台股	155733.00	18796.00	0.135500	155.9500	1000.00000	2026-01-05	2026
54	006208	富邦台50	46237.28	台股	56561.00	10402.32	0.223300	159.1000	356.00000	2026-01-06	2026
55	0050	元大台灣50	26012.00	台股	72275.00	46438.00	1.778500	72.4500	1000.00000	2026-01-30	2026
56	0050	元大台灣50	26012.00	台股	71078.00	45238.00	1.732500	71.2500	1000.00000	2026-02-06	2026
\.


--
-- Data for Name: stock_holding; Type: TABLE DATA; Schema: public; Owner: assets
--

COPY public.stock_holding (id, broker, currency, current_value, dividend_rate, estimated_dividend, investment_cost, market, original_currency_value, shares, stock_code, stock_name, snapshot_id) FROM stdin;
1	\N	TWD	132479.00	\N	\N	76450.00	台股	\N	1000.00000	0050	0050	1
2	華南證券	TWD	113356.00	\N	\N	92229.00	台股	\N	11000.00000	00642	元大石油	1
3	華南證券	TWD	37534.00	\N	\N	27900.00	台股	\N	1000.00000	2606	裕民	1
4	華南證券	TWD	518694.00	\N	\N	378863.00	台股	\N	9702.00000	2881	富邦金	1
5	華南證券	TWD	88806.00	\N	\N	77200.00	台股	\N	2000.00000	2882	國泰金	1
6	華南證券	TWD	36141.00	\N	\N	30950.00	台股	\N	1000.00000	9933	中鼎	1
7	\N	TWD	409855.00	\N	\N	360120.00	台股	\N	3000.00000	0050	元大台灣50	2
8	\N	TWD	157518.00	\N	\N	156434.00	台股	\N	2000.00000	006208	富邦台50	2
9	華南證券	TWD	662201.00	\N	\N	431350.00	台股	\N	8627.00000	2881	富邦金	2
10	華南證券	TWD	75876.00	\N	\N	76438.00	台股	\N	2000.00000	00679B	元大美債20年	2
11	華南證券	TWD	27794.00	\N	\N	26900.00	台股	\N	2000.00000	00882	中信中國高股息	2
12	華南證券	TWD	58641.00	\N	\N	58208.00	台股	\N	100.00000	2330	台積電	2
39	\N	TWD	2370849.60	\N	141065.5512	1065436.68	台股	\N	36141.00000	0050	元大台灣50	4
40	\N	TWD	899849.50	\N	27535.3947	499203.65	台股	\N	5995.00000	006208	富邦台50	4
41	\N	TWD	405531.84	\N	19100.5497	310302.72	台股	\N	12432.00000	00881	國泰台灣科技龍頭	4
42	\N	TWD	14690.00	\N	464.2040	13680.00	台股	\N	1000.00000	009804	聯邦台精彩50	4
43	\N	TWD	266659.80	\N	27359.2955	231448.80	台股	\N	7260.00000	0056	元大高股息	4
44	\N	TWD	242891.48	\N	20208.5711	216711.56	台股	\N	11188.00000	00878	國泰永續高股息	4
45	\N	TWD	292027.35	\N	26370.0697	305025.60	台股	\N	5777.00000	00713	元大高息低波	4
46	\N	TWD	99881.60	\N	12375.3302	94218.67	台股	\N	4459.00000	00919	群益台灣精選高息	4
47	\N	TWD	466373.30	\N	22712.3797	241582.34	台股	\N	4853.00000	2881	富邦金	4
48	\N	TWD	200800.00	\N	10542.0000	93720.00	台股	\N	4000.00000	2891	中信金	4
49	華南證券	TWD	274942.80	\N	12482.4031	209880.00	台股	\N	6996.00000	2885	元大金	4
50	華南證券	TWD	775000.00	\N	5967.5000	243900.00	台股	\N	500.00000	2330	台積電	4
51	華南證券	TWD	323039.16	\N	13826.0761	353161.02	台股	\N	11859.00000	00679B	元大美債20年	4
52	華南證券	TWD	162936.20	\N	8717.0867	165875.64	台股	\N	5068.00000	00751B	元大AAA至公司債	4
53	華南證券	TWD	15160.00	\N	1211.2840	10530.00	台股	\N	1000.00000	00882	中信中國高股息	4
54	國泰證券	TWD	41779.47	\N	0.0000	34897.00	美股	\N	5.76820	AMZN	亞馬遜	4
55	國泰證券	TWD	52871.95	\N	233.6940	29365.00	美股	\N	3.48390	MSFT	微軟	4
56	國泰證券	TWD	65901.78	\N	13.4440	33369.00	美股	\N	11.26070	NVDA	輝達	4
57	國泰證券	TWD	51808.62	\N	482.6491	23782.00	美股	\N	2.63260	VOO	S&P 500 ETF	4
58	國泰證券	TWD	57612.84	\N	536.7212	16010.08	美股	\N	2.92760	VOO	S&P 500 ETF (原幣)	4
59	國泰證券	TWD	21721.24	\N	116.6865	21876.38	美股	\N	2.00000	AVGO	Broadcom	4
60	富邦證券	TWD	1894272.75	\N	\N	1139660.29	台股	\N	9677.00000	0050	元大台灣50	5
61	富邦證券	TWD	861911.40	\N	\N	568740.66	台股	\N	7554.00000	006208	富邦台50	5
62	富邦證券	TWD	47503.37	\N	\N	46034.98	台股	\N	1907.00000	00881	國泰台灣5G+	5
63	華南證券	TWD	173313.00	\N	\N	153798.75	台股	\N	4725.00000	0056	元大高股息	5
64	華南證券	TWD	75234.56	\N	\N	54780.80	台股	\N	3392.00000	00878	國泰永續高股息	5
65	華南證券	TWD	165402.80	\N	\N	166554.24	台股	\N	3112.00000	00713	元大高息低波	5
66	華南證券	TWD	427570.50	\N	\N	259335.95	台股	\N	4735.00000	2881	富邦金	5
67	華南證券	TWD	156400.00	\N	\N	93720.00	台股	\N	4000.00000	2891	中信金	5
68	華南證券	TWD	537500.00	\N	\N	245900.00	台股	\N	500.00000	2330	台積電	5
69	華南證券	TWD	123500.00	\N	\N	119170.00	台股	\N	1000.00000	2412	中華電	5
70	元大證券	TWD	282460.35	\N	\N	322093.53	台股	\N	9859.00000	00679B	元大美債20年	5
71	元大證券	TWD	137539.08	\N	\N	133145.64	台股	\N	4068.00000	00751B	元大AAA至公司債	5
72	元大證券	TWD	39450.00	\N	\N	33180.00	台股	\N	3000.00000	00882	中信中國高股息	5
73	元大證券	TWD	13626.99	\N	\N	9809.67	美股	\N	1.65800	AAPL	蘋果公司	5
74	元大證券	TWD	36007.59	\N	\N	30870.45	美股	\N	5.00080	AMZN	亞馬遜	5
75	元大證券	TWD	73173.54	\N	\N	71401.06	美股	\N	5.28950	MSFT	微軟	5
76	元大證券	TWD	59401.72	\N	\N	54177.69	美股	\N	13.47770	NVDA	輝達	5
77	\N	TWD	1556799.00	\N	\N	1082683.08	台股	\N	9311.00000	0050	元大台灣50	6
78	\N	TWD	578771.00	\N	\N	429885.31	台股	\N	5927.00000	006208	富邦台50	6
79	華南證券	TWD	554238.00	\N	\N	411322.70	台股	\N	7510.00000	2881	富邦金	6
80	華南證券	TWD	276812.00	\N	\N	310700.16	台股	\N	9519.00000	00679B	元大美債20年	6
81	華南證券	TWD	37200.00	\N	\N	34380.00	台股	\N	3000.00000	00882	中信中國高股息	6
82	華南證券	TWD	417500.00	\N	\N	247650.00	台股	\N	500.00000	2330	台積電	6
83	華南證券	TWD	158640.00	\N	\N	113040.00	台股	\N	4000.00000	0056	元大高股息	6
84	華南證券	TWD	69060.00	\N	\N	49800.00	台股	\N	3000.00000	00878	國泰永續高股息	6
85	華南證券	TWD	115650.00	\N	\N	63600.00	台股	\N	3000.00000	2891	中信金	6
86	華南證券	TWD	112871.00	\N	\N	108372.00	台股	\N	3284.00000	00751B	元大AAA至A公司債	6
87	元大證券	TWD	54574.00	\N	\N	46766.72	台股	\N	1022.00000	00646	元大S&P500	6
88	元大證券	TWD	63034.00	\N	\N	53645.36	台股	\N	1102.00000	00713	元大高息低波	6
89	元大證券	TWD	10152.63	\N	\N	9639.30	美股	\N	1.65800	AAPL	蘋果公司	6
90	元大證券	TWD	8062.40	\N	\N	8183.32	美股	\N	1.35350	AMZN	亞馬遜	6
91	元大證券	TWD	38377.26	\N	\N	36487.67	美股	\N	2.83190	MSFT	微軟	6
92	\N	TWD	1143292.00	\N	\N	1083374.64	台股	\N	9333.00000	0050	元大台灣50	7
93	\N	TWD	507131.00	\N	\N	499563.00	台股	\N	7086.00000	006208	富邦台50	7
94	華南證券	TWD	557972.00	\N	\N	534422.00	台股	\N	9058.00000	2881	富邦金	7
95	華南證券	TWD	129040.00	\N	\N	143840.00	台股	\N	4000.00000	00679B	元大美債20年	7
96	華南證券	TWD	36600.00	\N	\N	36360.00	台股	\N	3000.00000	00882	中信中國高股息	7
97	華南證券	TWD	266000.00	\N	\N	252300.00	台股	\N	500.00000	2330	台積電	7
98	華南證券	TWD	117240.00	\N	\N	107000.00	台股	\N	4000.00000	0056	元大高股息	7
99	華南證券	TWD	90100.00	\N	\N	85900.00	台股	\N	5000.00000	00878	國泰永續高股息	7
100	華南證券	TWD	73200.00	\N	\N	66600.00	台股	\N	3000.00000	2891	中信金	7
101	華南證券	TWD	300000.00	\N	\N	335490.00	台股	\N	3000.00000	7556	意德士	7
102	\N	TWD	83598.00	\N	\N	76450.00	台股	\N	1000.00000	0050	元大台灣50	8
103	\N	TWD	29170.00	\N	\N	29300.00	台股	\N	1000.00000	006205	富邦上證	8
104	華南證券	TWD	114921.00	\N	\N	103200.00	台股	\N	12000.00000	00642	元大石油	8
105	華南證券	TWD	86018.00	\N	\N	90400.00	台股	\N	1000.00000	1301	台塑	8
106	華南證券	TWD	19813.00	\N	\N	22850.00	台股	\N	1000.00000	2002	中鋼	8
107	華南證券	TWD	209.00	\N	\N	555.00	台股	\N	30.00000	2409	友達	8
108	華南證券	TWD	28176.00	\N	\N	29800.00	台股	\N	1000.00000	2606	裕民	8
109	華南證券	TWD	408176.00	\N	\N	398267.10	台股	\N	9702.00000	2881	富邦金	8
110	華南證券	TWD	78950.00	\N	\N	81200.00	台股	\N	2000.00000	2882	國泰金	8
111	華南證券	TWD	34150.00	\N	\N	32950.00	台股	\N	1000.00000	9933	中鼎	8
745	元大證券	TWD	23894.00	\N	0.0000	28455.42	美股	\N	2.00000	MSFT	微軟	3
746	國泰證券	TWD	60365.00	\N	0.0000	69350.00	美股	\N	5.05270	MSFT	微軟	3
747	元大證券	TWD	11947.00	\N	0.0000	14227.71	美股	\N	1.00000	MSFT	微軟	3
748	國泰證券	TWD	63901.00	\N	0.0000	35768.00	美股	\N	11.26070	NVDA	輝達	3
749	國泰證券	TWD	18923.00	\N	0.0000	9500.00	美股	\N	2.00000	GOOGL	Google (原幣)	3
750	國泰證券	TWD	50782.00	\N	0.0000	46268.00	美股	\N	2.63260	VOO	S&P 500 ETF	3
751	國泰證券	TWD	106010.00	\N	0.0000	110269.15	美股	\N	5.49570	VOO	S&P 500 ETF	3
752	國泰證券	TWD	10158.00	\N	0.0000	20064.77	美股	\N	1.00000	AVGO	Broadcom (原幣, 富邦)	3
753	國泰證券	TWD	30475.00	\N	0.0000	32052.06	美股	\N	3.00000	AVGO	Broadcom (原幣, 富邦)	3
754	元大證券	TWD	25378.00	\N	0.0000	80984.85	美股	\N	5.69210	VT	Vanguard全世界股票ETF (原幣)	3
755	富邦證券	TWD	1996650.00	\N	0.0000	702270.00	台股	\N	27000.00000	0050	元大台灣50	3
756	國泰證券	TWD	15456.00	\N	0.0000	10874.00	台股	\N	209.00000	0050	元大台灣50	3
757	元大證券	TWD	512621.00	\N	0.0000	260297.00	台股	\N	6932.00000	0050	元大台灣50	3
758	富邦證券	TWD	487172.00	\N	0.0000	208922.00	台股	\N	2839.00000	006208	富邦台50	3
759	元大證券	TWD	308880.00	\N	0.0000	177138.00	台股	\N	1800.00000	006208	富邦台50	3
760	元大證券	TWD	44703.00	\N	0.0000	30071.00	台股	\N	1239.00000	00881	國泰台灣科技龍頭	3
761	國泰證券	TWD	350626.00	\N	0.0000	253834.00	台股	\N	9718.00000	00881	國泰台灣科技龍頭	3
762	富邦證券	TWD	72160.00	\N	0.0000	45440.00	台股	\N	2000.00000	00881	國泰台灣科技龍頭	3
763	國泰證券	TWD	32800.00	\N	0.0000	30360.00	台股	\N	2000.00000	009804	聯邦台精彩50	3
764	富邦證券	TWD	75640.00	\N	0.0000	46240.00	台股	\N	2000.00000	0056	元大高股息	3
765	元大證券	TWD	110472.00	\N	0.0000	110209.00	台股	\N	2921.00000	0056	元大高股息	3
766	國泰證券	TWD	101055.00	\N	0.0000	88710.00	台股	\N	2672.00000	0056	元大高股息	3
767	\N	TWD	246472.00	\N	0.0000	216711.56	台股	\N	11188.00000	00878	國泰永續高股息	3
768	富邦證券	TWD	112457.00	\N	0.0000	113902.00	台股	\N	2190.00000	00713	元大高息低波	3
769	元大證券	TWD	51350.00	\N	0.0000	52880.00	台股	\N	1000.00000	00713	元大高息低波	3
770	國泰證券	TWD	132842.00	\N	0.0000	134395.00	台股	\N	2587.00000	00713	元大高息低波	3
771	國泰證券	TWD	121736.00	\N	0.0000	119225.00	台股	\N	5459.00000	00919	群益台灣精選高息	3
772	富邦證券	TWD	44600.00	\N	0.0000	46700.00	台股	\N	2000.00000	00919	群益台灣精選高息	3
773	\N	TWD	426093.00	\N	0.0000	215619.00	台股	\N	4853.00000	2881	富邦金	3
774	\N	TWD	218000.00	\N	0.0000	92000.00	台股	\N	4000.00000	2891	中信金	3
775	富邦證券	TWD	320767.00	\N	0.0000	193230.00	台股	\N	6996.00000	2885	元大金	3
776	富邦證券	TWD	905000.00	\N	0.0000	237400.00	台股	\N	500.00000	2330	台積電	3
777	富邦證券	TWD	268066.00	\N	0.0000	300009.00	台股	\N	9859.00000	00679B	元大美債20年	3
778	元大證券	TWD	54380.00	\N	0.0000	50360.00	台股	\N	2000.00000	00679B	元大美債20年	3
779	富邦證券	TWD	65824.00	\N	0.0000	70312.00	台股	\N	2068.00000	00751B	元大AAA至公司債	3
780	元大證券	TWD	63660.00	\N	0.0000	60180.00	台股	\N	2000.00000	00751B	元大AAA至公司債	3
781	國泰證券	TWD	31830.00	\N	0.0000	29600.00	台股	\N	1000.00000	00751B	元大AAA至公司債	3
782	華南證券	TWD	15490.00	\N	0.0000	9980.00	台股	\N	1000.00000	00882	中信中國高股息	3
783	國泰證券	TWD	38707.00	\N	0.0000	37715.00	美股	\N	5.76820	AMZN	亞馬遜	3
\.


--
-- Name: asset_snapshot_id_seq; Type: SEQUENCE SET; Schema: public; Owner: assets
--

SELECT pg_catalog.setval('public.asset_snapshot_id_seq', 8, true);


--
-- Name: bank_deposit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: assets
--

SELECT pg_catalog.setval('public.bank_deposit_id_seq', 360, true);


--
-- Name: fund_holding_id_seq; Type: SEQUENCE SET; Schema: public; Owner: assets
--

SELECT pg_catalog.setval('public.fund_holding_id_seq', 241, true);


--
-- Name: realized_gain_id_seq; Type: SEQUENCE SET; Schema: public; Owner: assets
--

SELECT pg_catalog.setval('public.realized_gain_id_seq', 56, true);


--
-- Name: stock_holding_id_seq; Type: SEQUENCE SET; Schema: public; Owner: assets
--

SELECT pg_catalog.setval('public.stock_holding_id_seq', 783, true);


--
-- Name: asset_snapshot asset_snapshot_pkey; Type: CONSTRAINT; Schema: public; Owner: assets
--

ALTER TABLE ONLY public.asset_snapshot
    ADD CONSTRAINT asset_snapshot_pkey PRIMARY KEY (id);


--
-- Name: bank_deposit bank_deposit_pkey; Type: CONSTRAINT; Schema: public; Owner: assets
--

ALTER TABLE ONLY public.bank_deposit
    ADD CONSTRAINT bank_deposit_pkey PRIMARY KEY (id);


--
-- Name: fund_holding fund_holding_pkey; Type: CONSTRAINT; Schema: public; Owner: assets
--

ALTER TABLE ONLY public.fund_holding
    ADD CONSTRAINT fund_holding_pkey PRIMARY KEY (id);


--
-- Name: realized_gain realized_gain_pkey; Type: CONSTRAINT; Schema: public; Owner: assets
--

ALTER TABLE ONLY public.realized_gain
    ADD CONSTRAINT realized_gain_pkey PRIMARY KEY (id);


--
-- Name: stock_holding stock_holding_pkey; Type: CONSTRAINT; Schema: public; Owner: assets
--

ALTER TABLE ONLY public.stock_holding
    ADD CONSTRAINT stock_holding_pkey PRIMARY KEY (id);


--
-- Name: asset_snapshot uk543wceg5u97okprjcn4wq41x0; Type: CONSTRAINT; Schema: public; Owner: assets
--

ALTER TABLE ONLY public.asset_snapshot
    ADD CONSTRAINT uk543wceg5u97okprjcn4wq41x0 UNIQUE (snapshot_date);


--
-- Name: fund_holding fk2ic58t3gkyb93k5qiavdn43x6; Type: FK CONSTRAINT; Schema: public; Owner: assets
--

ALTER TABLE ONLY public.fund_holding
    ADD CONSTRAINT fk2ic58t3gkyb93k5qiavdn43x6 FOREIGN KEY (snapshot_id) REFERENCES public.asset_snapshot(id);


--
-- Name: stock_holding fk7mnwqhx8fc8nk9c0i0te8ocxc; Type: FK CONSTRAINT; Schema: public; Owner: assets
--

ALTER TABLE ONLY public.stock_holding
    ADD CONSTRAINT fk7mnwqhx8fc8nk9c0i0te8ocxc FOREIGN KEY (snapshot_id) REFERENCES public.asset_snapshot(id);


--
-- Name: bank_deposit fkjxcn193425e8y6bdobkkma5jo; Type: FK CONSTRAINT; Schema: public; Owner: assets
--

ALTER TABLE ONLY public.bank_deposit
    ADD CONSTRAINT fkjxcn193425e8y6bdobkkma5jo FOREIGN KEY (snapshot_id) REFERENCES public.asset_snapshot(id);


--
-- PostgreSQL database dump complete
--

\unrestrict inzkDak6p9JowMdIULhRSfhoZavj9aCCHdfX23DHYAcmphbooET1EZ61cguseYh

