package com.steven.assets.externalmaterials.service;

import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.testcontainers.containers.PostgreSQLContainer;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import static com.steven.assets.externalmaterials.service.FubonMarketData.*;
import static org.assertj.core.api.Assertions.*;

/** Requires Docker: validates Task425's actual PostgreSQL immutable fact and atomic source-authority race. */
class FubonHistoricalDailyCandlePostgresIntegrationTest {
    @Test void migrationMakesFactImmutableAndOfficialCloseWinsConcurrentFubonProjection() throws Exception {
        try (PostgreSQLContainer<?> pg = new PostgreSQLContainer<>("postgres:16-alpine")) {
            pg.start();
            var source = new DriverManagerDataSource(pg.getJdbcUrl(), pg.getUsername(), pg.getPassword());
            var jdbc = new JdbcTemplate(source);
            jdbc.execute("""
                    CREATE TABLE stock_price_history (
                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, stock_code varchar(20) NOT NULL, market varchar(20) NOT NULL,
                      trading_date date NOT NULL, open_price numeric(15,4), high_price numeric(15,4), low_price numeric(15,4),
                      close_price numeric(15,4) NOT NULL CHECK (close_price > 0), volume bigint, close_source varchar(64),
                      UNIQUE(stock_code, market, trading_date))
                    """);
            jdbc.execute("""
                    CREATE TABLE api_error_log_operation (
                      source varchar(16) NOT NULL, operation_key varchar(160) NOT NULL, operation_label varchar(255) NOT NULL,
                      display_order smallint NOT NULL, PRIMARY KEY(source, operation_key), UNIQUE(source, operation_key, operation_label))
                    """);
            jdbc.execute("""
                    CREATE TABLE api_error_log (
                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, source varchar(16) NOT NULL, operation_key varchar(160) NOT NULL,
                      api_name varchar(255) NOT NULL, message_header text NOT NULL, stack_trace text NOT NULL, occurred_at timestamptz NOT NULL,
                      FOREIGN KEY(source, operation_key, api_name) REFERENCES api_error_log_operation(source, operation_key, operation_label))
                    """);
            applyMigration(jdbc);
            assertThat(jdbc.update("INSERT INTO api_error_log (source,operation_key,api_name,message_header,stack_trace,occurred_at) VALUES ('FUBON_API','FUBON_INTRADAY_VOLUMES_READ','個股當日分價量查詢','test','trace',CURRENT_TIMESTAMP)"))
                    .isEqualTo(1);
            assertThat(jdbc.update("INSERT INTO api_error_log (source,operation_key,api_name,message_header,stack_trace,occurred_at) VALUES ('FUBON_API','FUBON_HISTORICAL_DAILY_CANDLES_READ','個股歷史日K線查詢','test','trace',CURRENT_TIMESTAMP)"))
                    .isEqualTo(1);
            var store = new FubonHistoricalDailyCandleStore(jdbc, new DataSourceTransactionManager(source));
            var read = daily();
            var candle = read.candles().getFirst();
            assertThat(store.persist(read, candle).status()).isEqualTo(FubonHistoricalDailyCandleStore.Status.WRITTEN);
            assertThat(store.persist(read, candle).status()).isEqualTo(FubonHistoricalDailyCandleStore.Status.UNCHANGED);
            assertThatThrownBy(() -> jdbc.update("UPDATE fubon_historical_daily_candle SET close=1 WHERE stock_code='2330'"))
                    .hasMessageContaining("immutable");
            assertThatThrownBy(() -> jdbc.update("DELETE FROM fubon_historical_daily_candle WHERE stock_code='2330'"))
                    .hasMessageContaining("immutable");

            var history = new StockSourceQuery(jdbc);
            var pool = Executors.newFixedThreadPool(2);
            pool.submit(() -> history.upsertFubonHistoricalDailyCandle("2330", candle.tradingDate(), candle.open(), candle.high(),
                    candle.low(), candle.close(), candle.volume()));
            pool.submit(() -> history.upsertVerifiedHistory("2330", MARKET, candle.tradingDate(), new BigDecimal("951"),
                    new BigDecimal("961"), new BigDecimal("946"), new BigDecimal("956"), 124L, "TWSE_MI_INDEX"));
            pool.shutdown(); assertThat(pool.awaitTermination(10, TimeUnit.SECONDS)).isTrue();
            assertThat(jdbc.queryForObject("SELECT close_source FROM stock_price_history WHERE stock_code='2330'", String.class))
                    .isEqualTo("TWSE_MI_INDEX");
            assertThat(history.upsertFubonHistoricalDailyCandle("2330", candle.tradingDate(), candle.open(), candle.high(),
                    candle.low(), candle.close(), candle.volume())).isFalse();
            assertThat(jdbc.queryForObject("SELECT close_price FROM stock_price_history WHERE stock_code='2330'", BigDecimal.class))
                    .isEqualByComparingTo("956");
        }
    }
    private static HistoricalDailyCandlesRead daily() {
        LocalDate date = LocalDate.of(2026, 8, 28);
        return new HistoricalDailyCandlesRead("2330", date.minusDays(365), date,
                Instant.parse("2026-08-28T05:40:00Z"), "TWSE", "TSE", "OK", null,
                List.of(new HistoricalDailyCandle(date, new BigDecimal("950"), new BigDecimal("960"), new BigDecimal("945"),
                        new BigDecimal("955"), 123L, new BigDecimal("117465"), new BigDecimal("5"))));
    }
    private static void applyMigration(JdbcTemplate jdbc) throws Exception {
        Path migration = migrationPath();
        String sql = Files.readString(migration).replaceAll("(?m)^--.*$", "").trim();
        jdbc.execute(sql);
    }
    private static Path migrationPath() {
        for (Path current = Path.of("").toAbsolutePath(); current != null; current = current.getParent()) {
            Path candidate = current.resolve(Path.of("backend", "src", "main", "resources", "db", "changelog",
                    "changes", "v1.128.0-fubon-volume-and-daily-candle.sql"));
            if (Files.isRegularFile(candidate)) return candidate;
        }
        throw new IllegalStateException("Task425 Liquibase migration is missing");
    }
}
