package com.steven.assets.service.srpp.decision;

import com.fasterxml.jackson.databind.*;
import org.junit.jupiter.api.Test;
import java.math.*;
import java.time.*;
import java.util.*;
import static com.steven.assets.service.srpp.decision.DecisionFacts.*;
import static org.assertj.core.api.Assertions.*;

class DailyDecisionCalculatorTest {
    static final Policy POLICY=new DecisionPolicyAuthority().policy();
    static final LocalDate DATE=LocalDate.parse("2026-10-08");
    static final Instant NOW=Instant.parse("2026-10-08T01:05:00Z");
    static final Evidence PASS=new Evidence("PASS","VERIFIED");
    static Input input(){return input(DATE,java.util.stream.IntStream.rangeClosed(1,20).mapToObj(i->DATE.minusDays(21-i)).toList(),Map.of("00865B",new BigDecimal("9.8"),"00719B",new BigDecimal("9.85"),"00697B",new BigDecimal("9.9")),Map.of());}
    static Input input(LocalDate date,List<LocalDate>sessions,Map<String,BigDecimal>price,Map<String,BigDecimal>premiums){return input(date,sessions,price,premiums,"09:05");}
    static Input input(LocalDate date,List<LocalDate>sessions,Map<String,BigDecimal>price,Map<String,BigDecimal>premiums,String slot){Instant at=date.atTime(LocalTime.parse(slot)).atZone(ZoneId.of("Asia/Taipei")).toInstant();Map<String,Symbol>symbols=new TreeMap<>();for(String c:POLICY.symbols()){
        Quote q=new Quote(price.get(c),BigDecimal.TEN,599L,date,at,"FUBON","LIVE",false,premiums.getOrDefault(c,BigDecimal.ZERO),date);
        List<Level>levels=new ArrayList<>();for(int i=0;i<5;i++)levels.add(new Level(q.price().subtract(new BigDecimal("0.01").multiply(BigDecimal.valueOf(i+1))),10,q.price().add(new BigDecimal("0.01").multiply(BigDecimal.valueOf(i+1))),10));
        symbols.put(c,new Symbol(c,q,new Book("FUBON_BOOKS",date,at,at,levels,true),sessions.stream().map(d->new Close(d,BigDecimal.TEN,true)).toList(),List.of(),true,BigDecimal.ZERO,PASS,PASS,PASS,PASS,PASS,"HOLD","HOLD",new Evidence("WAIT","TEST_SHORT_WAIT")));}
        return new Input(date,slot,at,sessions,new BigDecimal("20000000"),new BigDecimal("5000000"),new BigDecimal("1000000"),new BigDecimal("1000000"),new BigDecimal("32"),PASS,new Evidence("UNAVAILABLE","RESERVED_BEAR_WINDOW_SOURCE_UNAVAILABLE"),symbols,new Budget(0,0,0,true,BigDecimal.ZERO,Map.of(),BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO),PASS,BigDecimal.ZERO);}
    static Input symbol(Input in,String code,Symbol replacement){Map<String,Symbol>symbols=new HashMap<>(in.symbols());symbols.put(code,replacement);return new Input(in.date(),in.slot(),in.capturedAt(),in.sessions(),in.totalAssets(),in.totalDeposits(),in.termDeposits(),in.bondValue(),in.fx(),in.fxEvidence(),in.bearWindow(),symbols,in.budget(),in.subaccounts(),in.emergencyValue());}
    static Symbol replace(Symbol s,Quote q,BigDecimal value,Evidence tradability){return new Symbol(s.code(),q,s.book(),s.closes(),s.distributions(),s.distributionVerified(),value,s.position(),s.pending(),s.radar(),s.valuation(),tradability,s.mediumAction(),s.mediumCandidateAction(),s.intraday());}
    @Test void qualifiedSourcesProduceRealActionableFourLegReportAndShortWaitDoesNotDowngradeMedium(){Result r=DailyDecisionCalculator.calculate(POLICY,input());assertThat(r.ranking().getFirst()).isEqualTo("00865B");assertThat(r.candidates().getFirst().lots()).isEqualTo(2);assertThat(r.candidates().getLast().lots()).isEqualTo(2);assertThat(r.candidates().getFirst().receipts()).anySatisfy(v->{if(v.ruleId().equals("INTRADAY")){assertThat(v.status()).isEqualTo("NOT_APPLICABLE");assertThat(v.reason()).isEqualTo("HORIZON_NOT_APPLICABLE");}});}
    @Test void tradabilityBlockStopsEmergencyWhileUnavailableOnlyTightensItsPrice(){Input in=input();Symbol s=in.symbols().get("00865B");Result blocked=DailyDecisionCalculator.calculate(POLICY,symbol(in,s.code(),replace(s,s.quote(),s.currentValue(),new Evidence("BLOCK","ACTUAL_TRADABILITY_BLOCK"))));assertThat(blocked.candidates().getLast().lots()).isZero();assertThat(blocked.candidates().getLast().blockingReasons()).contains("ACTUAL_TRADABILITY_BLOCK");Result l2=DailyDecisionCalculator.calculate(POLICY,symbol(in,s.code(),replace(s,s.quote(),s.currentValue(),new Evidence("UNAVAILABLE","TRADABILITY_SOURCE_UNAVAILABLE"))));assertThat(l2.candidates().getLast().lots()).isEqualTo(2);assertThat(l2.candidates().getLast().limitPrice()).isEqualByComparingTo(s.book().levels().getFirst().ask());}
    @Test void firstRankedCapacityOneNeverSpillsSecond(){Input in=input();Symbol first=in.symbols().get("00865B");BigDecimal target=POLICY.targets().get(first.code()).multiply(in.totalAssets());Result r=DailyDecisionCalculator.calculate(POLICY,symbol(in,first.code(),replace(first,first.quote(),target.subtract(new BigDecimal("11000")),PASS)));assertThat(r.candidates().getFirst().lots()).isEqualTo(1);assertThat(r.candidates().get(1).lots()).isZero();}
    @Test void totalGroupBondCapLimitsAllBondLegs(){Input in=input();in=new Input(in.date(),in.slot(),in.capturedAt(),in.sessions(),in.totalAssets(),in.totalDeposits(),in.termDeposits(),new BigDecimal("6200000"),in.fx(),in.fxEvidence(),in.bearWindow(),in.symbols(),in.budget(),in.subaccounts(),in.emergencyValue());assertThat(DailyDecisionCalculator.calculate(POLICY,in).candidates()).allSatisfy(c->assertThat(c.lots()).isZero());}
    @Test void rawSuitabilityDoesNotRoundUpButEmergencyRoundedPercentMayReachOnePercent(){Input in=input();Symbol s=in.symbols().get("00865B");Quote q=s.quote();Quote near=new Quote(new BigDecimal("9.970004"),q.previousClose(),q.volume(),q.date(),q.updatedAt(),q.source(),q.status(),false,q.premium(),q.premiumDate());assertThat(DailyDecisionCalculator.quality(POLICY,in,replace(s,near,s.currentValue(),PASS)).suitable()).isFalse();Quote emergency=new Quote(new BigDecimal("9.900004"),q.previousClose(),q.volume(),q.date(),q.updatedAt(),q.source(),q.status(),false,q.premium(),q.premiumDate());Result r=DailyDecisionCalculator.calculate(POLICY,symbol(in,s.code(),replace(s,emergency,s.currentValue(),PASS)));assertThat(r.candidates().getLast().lots()).isEqualTo(2);}
    @Test void closedTrueAndMissingClosedCannotQualifyEvenEarlyQuote(){Input in=input();Quote q=in.symbols().get("00865B").quote();for(Boolean closed:new Boolean[]{true,null})assertThat(DailyDecisionCalculator.quoteQualified(POLICY,in,new Quote(q.price(),q.previousClose(),q.volume(),q.date(),q.updatedAt(),q.source(),q.status(),closed,q.premium(),q.premiumDate()))).isFalse();}
    @Test void explicitSharesNormalizeExactlyAndNeverFloorFractionalLots(){assertThat(DecisionInputCaptureAdapter.exactLots(599000L)).isEqualTo(599);assertThat(DecisionInputCaptureAdapter.exactLots(600000L)).isEqualTo(600);assertThat(DecisionInputCaptureAdapter.exactLots(599001L)).isNull();Input in=input();Quote q=in.symbols().get("00865B").quote();for(long shares:new long[]{599000,600000,599001}){Quote stale=new Quote(q.price(),q.previousClose(),DecisionInputCaptureAdapter.exactLots(shares),q.date(),q.updatedAt().minusSeconds(3600),q.source(),q.status(),false,q.premium(),q.premiumDate());assertThat(DailyDecisionCalculator.quoteQualified(POLICY,in,stale)).isEqualTo(shares==599000);}}
    @Test void fullPolicyRawBytesVerifyAndMutationFails(){DecisionPolicyAuthority a=new DecisionPolicyAuthority();assertThat(a.policy().bundleHash()).isEqualTo("919c7b79d79b62442063dac64f2aea14809d25ff75f7328147505013db70095f");assertThatThrownBy(()->new DecisionPolicyAuthority(a.modelBytes()+" ",a.manifestBytes())).isInstanceOf(IllegalStateException.class);}
    @Test void frozenCollectionsCannotBeMutated(){Input in=input();assertThatThrownBy(()->in.symbols().clear()).isInstanceOf(UnsupportedOperationException.class);assertThatThrownBy(()->in.sessions().clear()).isInstanceOf(UnsupportedOperationException.class);assertThatThrownBy(()->in.symbols().get("00865B").book().levels().clear()).isInstanceOf(UnsupportedOperationException.class);}
    @Test void twentyAuthoritySessionGoldenFieldsMatchOriginalD195()throws Exception{JsonNode fixture=new ObjectMapper().readTree(getClass().getResourceAsStream("/srpp/d195-authority-golden-20-sessions.json"));assertThat(fixture.get("sessions").size()).isEqualTo(20);for(JsonNode row:fixture.get("sessions")){LocalDate date=LocalDate.parse(row.get("date").textValue());List<LocalDate>sessions=new ArrayList<>();row.get("sessions").forEach(n->sessions.add(LocalDate.parse(n.textValue())));Map<String,BigDecimal>prices=new HashMap<>(),premiums=new HashMap<>();POLICY.symbols().forEach(c->{prices.put(c,new BigDecimal(row.get("prices").get(c).textValue()));premiums.put(c,new BigDecimal(row.get("premiums").get(c).textValue()));});for(String slot:List.of("09:05","11:40")){Input in=input(date,sessions,prices,premiums,slot);Result actual=DailyDecisionCalculator.calculate(POLICY,in);List<String>ranking=new ArrayList<>();row.get("expectedRanking").forEach(n->ranking.add(n.textValue()));assertThat(actual.ranking()).isEqualTo(ranking);assertThat(actual.candidates().stream().filter(c->c.strategy().equals("STRATEGIC_FUBON")).mapToInt(Candidate::lots).sum()).isEqualTo(row.get("expectedStrategicLots").intValue());assertThat(actual.candidates().getLast().lots()).isEqualTo(row.get("expectedEmergencyLots").intValue());for(String c:POLICY.symbols()){var q=DailyDecisionCalculator.quality(POLICY,in,in.symbols().get(c));JsonNode expected=row.get("expectedQuality").get(c);assertThat(q.suitable()).isEqualTo(expected.get("suitable").booleanValue());assertThat(q.reason()).isEqualTo(expected.get("reason").textValue());assertThat(q.high()).isEqualByComparingTo(expected.get("referenceHigh").textValue());assertThat(q.drawdownPercent()).isEqualByComparingTo(expected.get("drawdownPercent").textValue());}}}}
    @Test void sameRoundSecondLegAndPriorSlotReservationsRespectCombinedExposure(){Input base=input();Input narrow=new Input(base.date(),base.slot(),base.capturedAt(),base.sessions(),new BigDecimal("10000000"),base.totalDeposits(),base.termDeposits(),new BigDecimal("3061000"),base.fx(),base.fxEvidence(),base.bearWindow(),base.symbols(),base.budget(),base.subaccounts(),base.emergencyValue());Result actual=DailyDecisionCalculator.calculate(POLICY,narrow);BigDecimal amounts=actual.candidates().stream().map(c->c.amountTwd()==null?BigDecimal.ZERO:c.amountTwd()).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal fees=amounts.multiply(POLICY.feeRate()).setScale(2,RoundingMode.CEILING);assertThat(narrow.bondValue().add(amounts)).isLessThanOrEqualTo(narrow.totalAssets().subtract(fees).multiply(POLICY.totalBondCap()));Symbol chosen=base.symbols().get("00865B");BigDecimal target=POLICY.targets().get(chosen.code()).multiply(base.totalAssets());Input room=symbol(base,chosen.code(),replace(chosen,chosen.quote(),target.subtract(new BigDecimal("12000")),PASS));Budget reserved=new Budget(1,1,0,true,new BigDecimal("9813.98"),Map.of("00865B",new BigDecimal("9810")),BigDecimal.ZERO,new BigDecimal("9810"),new BigDecimal("13.98"));Input next=new Input(room.date(),"11:40",room.capturedAt(),room.sessions(),room.totalAssets(),room.totalDeposits(),room.termDeposits(),room.bondValue(),room.fx(),room.fxEvidence(),room.bearWindow(),room.symbols(),reserved,room.subaccounts(),room.emergencyValue());assertThat(DailyDecisionCalculator.calculate(POLICY,next).candidates().getFirst().lots()).isZero();}
    @Test void additiveCashDistributionUsesCompletedWindowAndRejectsConflictingOrStockRights(){Input in=input();Symbol s=in.symbols().get("00865B");List<Close>closes=new ArrayList<>(s.closes());closes.set(0,new Close(in.sessions().getFirst(),new BigDecimal("11"),true));Distribution cash=new Distribution(in.sessions().get(10),null,new BigDecimal("0.5"),BigDecimal.ZERO,"TWSE");Symbol adjusted=new Symbol(s.code(),s.quote(),s.book(),closes,List.of(cash),true,s.currentValue(),s.position(),s.pending(),s.radar(),s.valuation(),s.tradability(),s.mediumAction(),s.mediumCandidateAction(),s.intraday());var quality=DailyDecisionCalculator.quality(POLICY,in,adjusted);assertThat(quality.high()).isEqualByComparingTo("10.5");assertThat(quality.rawDrawdown()).isEqualByComparingTo(new BigDecimal("9.8").divide(new BigDecimal("10.5"),MathContext.DECIMAL128).subtract(BigDecimal.ONE));for(Distribution bad:List.of(new Distribution(cash.exDate(),null,new BigDecimal("0.6"),BigDecimal.ZERO,"TWSE"),new Distribution(cash.exDate(),cash.exDate(),BigDecimal.ZERO,BigDecimal.ONE,"TWSE"))){Symbol conflict=new Symbol(s.code(),s.quote(),s.book(),closes,List.of(cash,bad),true,s.currentValue(),s.position(),s.pending(),s.radar(),s.valuation(),s.tradability(),s.mediumAction(),s.mediumCandidateAction(),s.intraday());assertThat(DailyDecisionCalculator.quality(POLICY,in,conflict).suitable()).isFalse();}}

    @Test void missingBookSourceRemainsUnqualifiedInsteadOfThrowing(){Input in=input();Book b=in.symbols().get("00865B").book();assertThat(DailyDecisionCalculator.bookQualified(POLICY,in,new Book(null,b.date(),b.sourceTime(),b.fetchedAt(),b.levels(),true))).isFalse();}

}
