package com.steven.assets.service.srpp.decision;

import com.fasterxml.jackson.databind.node.*;
import com.steven.assets.repository.SrppDecisionRepository;
import com.steven.assets.repository.SrppDecisionRepository.*;
import com.steven.assets.security.CurrentUserContext;
import com.steven.assets.service.MarketDataService;
import com.steven.assets.service.srpp.*;
import com.steven.assets.srpp.*;
import org.junit.jupiter.api.*;
import org.springframework.http.HttpStatus;
import org.springframework.transaction.*;
import org.springframework.transaction.support.SimpleTransactionStatus;
import java.nio.file.*;
import java.time.*;
import java.util.*;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.*;
import static com.steven.assets.service.srpp.decision.DailyDecisionCalculatorTest.*;

class DailyDecisionCaptureServiceTest {
    static final String SWAGGER="b".repeat(64);
    CurrentUserContext owner;MarketDataService market;SrppPolicyRegistryService registry;PublishedSwaggerIdentity swagger;SrppDecisionRepository repository;DecisionInputCapturePort capture;DailyDecisionCaptureService service;
    @BeforeEach void setup(){owner=mock(CurrentUserContext.class);market=mock(MarketDataService.class);registry=mock(SrppPolicyRegistryService.class);swagger=mock(PublishedSwaggerIdentity.class);repository=mock(SrppDecisionRepository.class);capture=mock(DecisionInputCapturePort.class);PlatformTransactionManager manager=mock(PlatformTransactionManager.class);when(manager.getTransaction(any())).thenAnswer(i->new SimpleTransactionStatus());when(owner.hasUser()).thenReturn(true);when(owner.getStatus()).thenReturn("ACTIVE");when(owner.getEffectiveUserId()).thenReturn(7L);when(market.isTwTradingDayCachedOnly(DATE)).thenReturn(Optional.of(true));when(registry.find(POLICY.bundleHash())).thenReturn(Optional.of(mock(SupportedPolicy.class)));when(swagger.sha256()).thenReturn(Optional.of(SWAGGER));when(repository.scopeLock(7,DATE)).thenReturn(true);when(capture.capture(eq(7L),any(),any())).thenReturn(frozen());service=new DailyDecisionCaptureService(owner,market,registry,swagger,new DecisionPolicyAuthority(),repository,capture,manager,Clock.fixed(NOW.plusSeconds(1),ZoneOffset.UTC),"fixture-build");}
    static String body(){return "{\"tradingDate\":\"2026-10-08\",\"slot\":\"09:05\",\"policyBundleSha256\":\""+POLICY.bundleHash()+"\",\"swaggerSha256\":\""+SWAGGER+"\"}";}
    static DecisionInputCapturePort.Frozen frozen(){ObjectNode input=JsonNodeFactory.instance.objectNode();input.put("schemaVersion",1);input.put("ownerUserId",7);input.put("tradingDate",DATE.toString());input.put("slot","09:05");input.put("capturedAt",NOW.toString());ObjectNode sources=input.putObject("sources"),vector=JsonNodeFactory.instance.objectNode();Set<String>keys=new TreeSet<>(List.of("assets","calendar","policy","swagger","ledger","reservations","fx","bear-window","subaccounts","classifications"));for(String code:POLICY.symbols())for(String source:List.of("quote","book","radar","daily","dividends","pending","tradability","minute"))keys.add(source+":"+code);for(String key:keys){ObjectNode source=sources.putObject(key);source.put("fixture","verified-positive-source");ObjectNode receipt=vector.putObject(key);receipt.put("sourceId",key);receipt.put("revision","fixture-v1");receipt.put("capturedAt",NOW.toString());receipt.put("sha256",SrppJcs.hash(source));receipt.put("coverage","COMPLETE");receipt.put("validation","VERIFIED");}return new DecisionInputCapturePort.Frozen(input(),input,vector,9,NOW.toString());}
    @Test void holidayStopsBeforeRepositoriesPolicyOrCapture(){when(market.isTwTradingDayCachedOnly(DATE)).thenReturn(Optional.of(false));assertThatThrownBy(()->service.evaluate(body())).isInstanceOfSatisfying(SrppCaptureProblem.class,p->assertThat(p.code).isEqualTo("NON_TRADING_DAY"));verifyNoInteractions(repository,capture,swagger,registry);}
    @Test void activeClaimReturns202WithoutReadingCurrentPolicyOrSources(){Claim c=new Claim(UUID.randomUUID(),7,DATE,"09:05",POLICY.bundleHash(),SWAGGER,UUID.randomUUID(),NOW,NOW.plusSeconds(20));when(repository.claim(7,DATE,"09:05",false)).thenReturn(Optional.of(c));assertThat(service.evaluate(body()).status()).isEqualTo(HttpStatus.ACCEPTED);verifyNoInteractions(capture,registry,swagger);}
    @Test void createdFinalIsRealAndReplayDoesNotReadChangedSwaggerOrRecapture()throws Exception{final Claim[] own=new Claim[1];doAnswer(i->{own[0]=i.getArgument(0);when(repository.claim(7,DATE,"09:05",true)).thenReturn(Optional.of(own[0]));return null;}).when(repository).insertClaim(any());var result=service.evaluate(body());assertThat(result.status()).isEqualTo(HttpStatus.CREATED);var cap=org.mockito.ArgumentCaptor.forClass(Run.class);verify(repository).insert(cap.capture());Run run=cap.getValue();ObjectNode n=(ObjectNode)SrppJcs.parseStrict(result.body());assertThat(n.path("decision").path("candidates").get(0).path("lots").asInt()).isEqualTo(2);Files.writeString(Path.of("/tmp/task488-decision-positive.json"),result.body());when(repository.find(7,DATE,"09:05")).thenReturn(Optional.of(run));clearInvocations(capture,swagger,registry);var replay=service.evaluate(body());assertThat(replay.status()).isEqualTo(HttpStatus.OK);assertThat(SrppJcs.parseStrict(replay.body()).path("decisionContentSha256")).isEqualTo(n.path("decisionContentSha256"));verifyNoInteractions(capture,swagger,registry);}
    @Test void replayRejectsTwoIndividuallyValidButDifferentInputBundles(){ObjectNode content=JsonNodeFactory.instance.objectNode();content.put("schemaVersion",1);UUID id=UUID.randomUUID();content.put("decisionRunId",id.toString());content.put("status","FINAL");ObjectNode identity=content.putObject("identity");identity.put("ownerUserId",7);identity.put("tradingDate",DATE.toString());identity.put("slot","09:05");identity.put("policyBundleSha256",POLICY.bundleHash());identity.put("swaggerSha256",SWAGGER);content.putObject("inputSnapshot").put("inputBundleJcs","{}").put("inputSnapshotSha256",SrppJcs.sha256Hex("{}"));String hash=SrppJcs.hash(content);content.put("decisionContentSha256",hash);Run r=new Run(id,7,DATE,"09:05",POLICY.bundleHash(),SWAGGER,"{\"different\":true}",SrppJcs.sha256Hex("{\"different\":true}"),SrppJcs.canonicalize(content),hash,NOW,NOW);assertThatThrownBy(()->DailyDecisionCaptureService.replay(r)).isInstanceOfSatisfying(SrppCaptureProblem.class,p->assertThat(p.code).isEqualTo("UPSTREAM_INVALID"));}
    @Test void oldSlotMetadataMismatchIs409WithoutCurrentRegistry(){Run r=new Run(UUID.randomUUID(),7,DATE,"09:05",POLICY.bundleHash(),"c".repeat(64),"{}","a","{}","a",NOW,NOW);when(repository.find(7,DATE,"09:05")).thenReturn(Optional.of(r));assertThatThrownBy(()->service.evaluate(body())).isInstanceOfSatisfying(SrppCaptureProblem.class,p->assertThat(p.code).isEqualTo("RUN_METADATA_MISMATCH"));verifyNoInteractions(capture,swagger,registry);}
}
