package com.steven.assets.service.srpp.decision;

import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import com.steven.assets.dto.*;
import com.steven.assets.model.*;
import com.steven.assets.repository.*;
import com.steven.assets.service.*;
import com.steven.assets.service.srpp.SrppCaptureProblem;
import org.junit.jupiter.api.*;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;

/** Cache-only/source boundary tests: no broker/network/database write. */
class DecisionInputCaptureAdapterTest {
    LatestAssetsService assets;PriceQueryService prices;MarketDataService market;TradingRadarService radar;StockPriceHistoryRepository histories;StockDividendHistoryRepository dividends;SrppDecisionSourceRepository ledger;UsdTwdLiveRateService fx;RadarIntradayCandlePort minutes;StockRepository masters;FundClassOverrideRepository funds;DecisionInputCaptureAdapter adapter;AssetSnapshotDto.SnapshotDetailResponse snapshot;LatestAssetsDto.Response response;LocalDate date;
    @BeforeEach void setup(){date=LocalDate.now(ZoneId.of("Asia/Taipei"));assets=mock(LatestAssetsService.class);prices=mock(PriceQueryService.class);market=mock(MarketDataService.class);radar=mock(TradingRadarService.class);histories=mock(StockPriceHistoryRepository.class);dividends=mock(StockDividendHistoryRepository.class);ledger=mock(SrppDecisionSourceRepository.class);fx=mock(UsdTwdLiveRateService.class);minutes=mock(RadarIntradayCandlePort.class);masters=mock(StockRepository.class);funds=mock(FundClassOverrideRepository.class);snapshot=mock(AssetSnapshotDto.SnapshotDetailResponse.class);AssetSnapshotDto.DepositResponse deposit=new AssetSnapshotDto.DepositResponse(1L,1L,"fixturebank","TERM_TWD","term",new BigDecimal("5000000"),new BigDecimal("5000000"),"TWD",null,null,null,"MANUAL",date);AssetSnapshotDto.FundResponse fund=new AssetSnapshotDto.FundResponse(2L,"未知分類基金","24B2",1L,"fixturebank",BigDecimal.ZERO,new BigDecimal("1000000"),BigDecimal.ONE,null,null,null,null);when(snapshot.id()).thenReturn(9L);when(snapshot.deposits()).thenReturn(List.of(deposit));when(snapshot.funds()).thenReturn(List.of(fund));when(snapshot.stocks()).thenReturn(List.of());when(snapshot.totalDeposit()).thenReturn(new BigDecimal("5000000"));when(snapshot.totalFundValue()).thenReturn(new BigDecimal("1000000"));when(snapshot.totalStockValue()).thenReturn(BigDecimal.ZERO);var live=new StockPriceService.LiveAssetsResponse(9L,date.toString(),new BigDecimal("32"),new BigDecimal("5000000"),new BigDecimal("1000000"),BigDecimal.ZERO,new BigDecimal("6000000"),List.of(),true,false,false,null);response=new LatestAssetsDto.Response(Instant.now(),"CURRENT",true,Map.of(),snapshot,live);when(assets.getLatestForOwner(7)).thenReturn(response);when(market.isTwTradingDayCachedOnly(any())).thenReturn(Optional.of(true));when(prices.getLiveBatch(any(),any())).thenReturn(Map.of());when(prices.getEtfNavBatch(any())).thenReturn(Map.of());when(ledger.ledger(eq(7L),any(),any())).thenReturn(JsonNodeFactory.instance.arrayNode());when(masters.findAllByCodeIn(any())).thenReturn(List.of());when(funds.findAllById(any())).thenReturn(List.of(new FundClassOverride("未知分類基金","BOND",null,null)));when(minutes.read(any(),any(),any())).thenReturn(Map.of());adapter=new DecisionInputCaptureAdapter(assets,prices,market,radar,histories,dividends,ledger,fx,minutes,new DecisionPolicyAuthority(),new ObjectMapper().findAndRegisterModules(),masters,funds);}
    DecisionRequest request(){return new DecisionRequest(null,date,"09:05",DailyDecisionCalculatorTest.POLICY.bundleHash(),"b".repeat(64));}
    @Test void canonicalFundOverrideIsIncludedAndRawSourceFrozenBeforeMinuteFrame(){var f=adapter.capture(7,request(),List.of());assertThat(f.facts().bondValue()).isEqualByComparingTo("1000000");assertThat(f.input().path("sources").path("classifications").path("fundOverrideRows").get(0).path("assetClass").asText()).isEqualTo("BOND");var order=inOrder(assets,masters,funds,minutes);order.verify(assets).getLatestForOwner(7);order.verify(masters).findAllByCodeIn(any());order.verify(funds).findAllById(any());order.verify(minutes).read(any(),eq(date),eq(f.facts().capturedAt()));assertThat(f.facts().capturedAt()).isAfterOrEqualTo(response.generatedAt());ObjectNode copy=f.input();copy.removeAll();assertThat(f.input().has("sources")).isTrue();}
    @Test void wrongQuoteAndNavSelectorAreFrozenAsUnavailable(){var key=new PriceQueryService.PriceKey("00719B","台股");PriceQueryService.LivePrice wrong=mock(PriceQueryService.LivePrice.class);when(wrong.stockCode()).thenReturn("00865B");when(wrong.market()).thenReturn("台股");when(wrong.closed()).thenReturn(false);when(prices.getLiveBatch(any(),any())).thenReturn(Map.of(key,Optional.of(wrong)));when(prices.getEtfNavBatch(any())).thenReturn(Map.of(key,Optional.of(new PriceQueryService.EtfNav("00697B","台股",BigDecimal.TEN,BigDecimal.ZERO,date.toString(),"FUBON"))));var f=adapter.capture(7,request(),List.of());assertThat(f.facts().symbols().get("00719B").quote()).isNull();assertThat(f.sourceVector().path("quote:00719B").path("validation").asText()).isEqualTo("UNAVAILABLE");assertThat(f.input().path("sources").path("quote:00719B").path("rawNav").path("stockCode").asText()).isEqualTo("00697B");}
    @Test void staleQuoteFxDailyAndPartialBookCannotClaimVerifiedSources(){var key=new PriceQueryService.PriceKey("00719B","台股");PriceQueryService.LivePrice q=new PriceQueryService.LivePrice("00719B","fixture","台股",BigDecimal.TEN,BigDecimal.ONE,null,null,null,null,null,null,null,600000L,date.toString(),Instant.now().minusSeconds(600).toString(),false,"FUBON","LIVE");when(prices.getLiveBatch(any(),any())).thenReturn(Map.of(key,Optional.of(q)));var book=mock(QuoteDetailDto.Response.class);when(book.stockCode()).thenReturn("00719B");when(book.market()).thenReturn("台股");when(book.available()).thenReturn(true);when(book.marketStatus()).thenReturn("OPEN");when(book.levels()).thenReturn(List.of());when(market.getQuoteDetail("00719B","台股")).thenReturn(book);var f=adapter.capture(7,request(),List.of());for(String keyName:List.of("quote:00719B","book:00719B","fx","daily:00719B"))assertThat(f.sourceVector().path(keyName).path("validation").asText()).isEqualTo("UNAVAILABLE");assertThat(f.input().path("sources").path("quote:00719B").path("rawVolumeUnit").asText()).isEqualTo("SHARES");assertThat(f.facts().symbols().get("00719B").quote().volume()).isEqualTo(600);}
    @Test void duplicateFundsAndNonTransitNegativeDepositsFailL0BeforeOtherSources(){var duplicate=snapshot.funds().getFirst();when(snapshot.funds()).thenReturn(List.of(duplicate,duplicate));assertThatThrownBy(()->adapter.capture(7,request(),List.of())).isInstanceOf(SrppCaptureProblem.class);verifyNoInteractions(prices,minutes,ledger,masters,funds);}
    @Test void negativeNonTransitDepositFailsL0(){var bad=new AssetSnapshotDto.DepositResponse(1L,1L,"bank","TERM_TWD","term",BigDecimal.ONE.negate(),BigDecimal.ONE.negate(),"TWD",null,null,null,"MANUAL",date);when(snapshot.deposits()).thenReturn(List.of(bad));assertThatThrownBy(()->adapter.capture(7,request(),List.of())).isInstanceOf(SrppCaptureProblem.class);verifyNoInteractions(prices,minutes,ledger,masters,funds);}
    @Test void fxSourceFutureAndFrameAgeCannotPass(){Instant at=Instant.now();var future=new UsdTwdLiveRateService.LiveRate("USD/TWD","USD","TWD",date,new BigDecimal("32"),new BigDecimal("32"),"MEGA_BANK",at,at.plusSeconds(1),"ACTIVE","LIVE");assertThat(DecisionInputCaptureAdapter.fxQualified(future,date,at)).isFalse();var stale=new UsdTwdLiveRateService.LiveRate("USD/TWD","USD","TWD",date,new BigDecimal("32"),new BigDecimal("32"),"MEGA_BANK",at.minusSeconds(7),at.minusSeconds(7),"ACTIVE","LIVE");assertThat(DecisionInputCaptureAdapter.fxQualified(stale,date,at)).isFalse();}

}
