--liquibase formatted sql

--changeset steven:v1.0.0-initial-schema
CREATE TABLE IF NOT EXISTS asset_snapshot (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_date             DATE           NOT NULL UNIQUE,
    usd_exchange_rate         NUMERIC(10,4),
    total_deposit             NUMERIC(20,2),
    total_fund_value          NUMERIC(20,2),
    total_fund_cost           NUMERIC(20,2),
    total_stock_value         NUMERIC(20,2),
    total_stock_cost          NUMERIC(20,2),
    total_assets              NUMERIC(20,2),
    estimated_annual_dividend NUMERIC(20,2),
    realized_gain             NUMERIC(20,2),
    notes                     VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS bank (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(50)  NOT NULL UNIQUE,
    display_name VARCHAR(50)  NOT NULL,
    keywords     VARCHAR(200),
    active       BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS broker (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(50)  NOT NULL UNIQUE,
    display_name VARCHAR(50)  NOT NULL,
    keywords     VARCHAR(200),
    active       BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS deposit_type (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(30)  NOT NULL UNIQUE,
    display_name VARCHAR(50)  NOT NULL,
    sort_order   INTEGER      NOT NULL,
    active       BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS market_type (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(20)  NOT NULL UNIQUE,
    display_name VARCHAR(50)  NOT NULL,
    sort_order   INTEGER      NOT NULL,
    active       BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS bank_deposit (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id     BIGINT         NOT NULL REFERENCES asset_snapshot(id),
    bank_id         BIGINT         REFERENCES bank(id),
    bank_name       VARCHAR(30),
    deposit_type    VARCHAR(30)    NOT NULL,
    amount          NUMERIC(20,2)  NOT NULL,
    original_amount NUMERIC(20,4),
    currency        VARCHAR(3)     DEFAULT 'TWD',
    notes           VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS fund_holding (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id       BIGINT         NOT NULL REFERENCES asset_snapshot(id),
    bank_id           BIGINT         REFERENCES bank(id),
    bank              VARCHAR(30),
    fund_code         VARCHAR(20),
    fund_name         VARCHAR(100)   NOT NULL,
    investment_amount NUMERIC(20,2)  NOT NULL,
    current_value     NUMERIC(20,2)  NOT NULL
);

CREATE TABLE IF NOT EXISTS stock_holding (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id             BIGINT         NOT NULL REFERENCES asset_snapshot(id),
    broker_id               BIGINT         REFERENCES broker(id),
    broker                  VARCHAR(30),
    stock_code              VARCHAR(20)    NOT NULL,
    stock_name              VARCHAR(50)    NOT NULL,
    market                  VARCHAR(20)    NOT NULL,
    shares                  NUMERIC(15,5)  NOT NULL,
    investment_cost         NUMERIC(20,2)  NOT NULL,
    current_value           NUMERIC(20,2)  NOT NULL,
    dividend_rate           NUMERIC(10,6),
    estimated_dividend      NUMERIC(20,4),
    currency                VARCHAR(3)     DEFAULT 'TWD',
    original_currency_value NUMERIC(20,4)
);

CREATE TABLE IF NOT EXISTS realized_gain (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_code      VARCHAR(20),
    asset_name      VARCHAR(50)    NOT NULL,
    market          VARCHAR(20),
    currency        VARCHAR(10),
    broker          VARCHAR(30),
    trade_date      DATE           NOT NULL,
    trade_year      INTEGER        NOT NULL,
    shares          NUMERIC(15,5),
    sale_price      NUMERIC(15,4),
    proceeds        NUMERIC(20,2)  NOT NULL,
    investment_cost NUMERIC(20,2)  NOT NULL,
    profit          NUMERIC(20,2)  NOT NULL,
    exchange_rate   NUMERIC(10,4),
    profit_rate     NUMERIC(10,6)
);

CREATE TABLE IF NOT EXISTS stock_price (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_code     VARCHAR(20),
    stock_name     VARCHAR(50)    NOT NULL,
    market         VARCHAR(20)    NOT NULL,
    price          NUMERIC(20,4)  NOT NULL,
    price_change   NUMERIC(20,4)  NOT NULL,
    change_percent NUMERIC(20,4)  NOT NULL,
    source         VARCHAR(50),
    trading_date   DATE,
    updated_at     TIMESTAMP      NOT NULL,
    closed         BOOLEAN
);

CREATE TABLE IF NOT EXISTS stock_price_history (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_code   VARCHAR(20),
    market       VARCHAR(20),
    trading_date DATE           NOT NULL,
    open_price   NUMERIC(20,4)  NOT NULL,
    high_price   NUMERIC(20,4)  NOT NULL,
    low_price    NUMERIC(20,4),
    close_price  NUMERIC(20,4)  NOT NULL,
    volume       BIGINT         NOT NULL
);

CREATE TABLE IF NOT EXISTS exchange_rate_history (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency  VARCHAR(10)    NOT NULL,
    rate_date DATE           NOT NULL,
    buy_rate  NUMERIC(10,4)  NOT NULL,
    mid_rate  NUMERIC(10,4)  NOT NULL,
    sell_rate NUMERIC(10,4)  NOT NULL
);
