--liquibase formatted sql

--changeset steven:v1.19.0-fund-master-and-nav
--comment 信託基金主檔 + 淨值快取 + fund_holding 加 units 欄位 (Requirement 19)
-- 業務資料 seed（fund_master 7 筆）由 DataInitializer 處理；本 changeset 只建 schema

CREATE TABLE fund_master (
    fund_code              VARCHAR(20)  PRIMARY KEY,
    fund_name              VARCHAR(150) NOT NULL,
    bank_id                BIGINT       REFERENCES bank(id),
    currency               VARCHAR(3)   NOT NULL,
    site                   VARCHAR(10)  NOT NULL,
    fundclear_org_code     VARCHAR(20)  NOT NULL,
    fundclear_fund_code    VARCHAR(20)  NOT NULL,
    fundclear_class_code   VARCHAR(20)  NOT NULL,
    active                 BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE fund_nav (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fund_code   VARCHAR(20)    NOT NULL,
    nav_date    DATE           NOT NULL,
    nav         NUMERIC(20,6)  NOT NULL,
    source      VARCHAR(20)    NOT NULL,
    fetched_at  TIMESTAMP      NOT NULL,
    CONSTRAINT uk_fund_nav_code_date UNIQUE (fund_code, nav_date)
);

CREATE INDEX idx_fund_nav_code_date ON fund_nav (fund_code, nav_date DESC);

ALTER TABLE fund_holding ADD COLUMN units NUMERIC(20,4);
