--liquibase formatted sql

--changeset codex:v1.123.0-api-error-log splitStatements:false
CREATE TABLE IF NOT EXISTS api_error_log_operation (
    source VARCHAR(16) NOT NULL CHECK (source IN ('OPEN_API', 'FUBON_API')),
    operation_key VARCHAR(160) NOT NULL,
    operation_label VARCHAR(255) NOT NULL,
    display_order SMALLINT NOT NULL CHECK (display_order > 0),
    PRIMARY KEY (source, operation_key),
    UNIQUE (source, operation_key, operation_label)
);

CREATE TABLE IF NOT EXISTS api_error_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(16) NOT NULL CHECK (source IN ('OPEN_API', 'FUBON_API')),
    operation_key VARCHAR(160) NOT NULL,
    api_name VARCHAR(255) NOT NULL,
    message_header TEXT NOT NULL,
    stack_trace TEXT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (source, operation_key, api_name)
        REFERENCES api_error_log_operation (source, operation_key, operation_label)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_api_error_log_source_operation_time
    ON api_error_log (source, operation_key, occurred_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_api_error_log_source_name_time
    ON api_error_log (source, api_name, occurred_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_api_error_log_time ON api_error_log (occurred_at DESC, id DESC);

INSERT INTO api_error_log_operation (source, operation_key, operation_label, display_order) VALUES
 ('OPEN_API','OPEN_QUOTES_LIST','即時報價清單',10),
 ('OPEN_API','OPEN_QUOTES_ONE','單一即時報價',20),
 ('OPEN_API','OPEN_MARKET_INDEX','大盤指數',30),
 ('OPEN_API','OPEN_LATEST_ASSETS','最新資產',40),
 ('OPEN_API','OPEN_USD_TWD','美元兌台幣',50),
 ('OPEN_API','OPEN_MARKET_ANALYSIS_TODAY','今日市場分析',60),
 ('OPEN_API','OPEN_PORTFOLIO_ADVICE_LATEST','最新資產配置建議',70),
 ('OPEN_API','OPEN_TRADING_RADAR_TODAY','今日交易雷達',80),
 ('OPEN_API','OPEN_TRADING_RADAR_STOCK','單一標的交易雷達',90),
 ('OPEN_API','OPEN_TRANSACTIONS','公開交易紀錄',100),
 ('OPEN_API','OPEN_TRADING_CALENDAR','交易日曆',110),
 ('OPEN_API','OPEN_COMMODITY_PRICES','油價金價',120),
 ('OPEN_API','OPEN_CRAWLER_RESCAN','公開爬蟲重新掃描',130),
 ('FUBON_API','FUBON_PORTFOLIO_READ','庫存與未實現損益',10),
 ('FUBON_API','FUBON_TW_QUOTES_INVENTORY','庫存同步台股報價',20),
 ('FUBON_API','FUBON_FILLED_TRADES_READ','已成交交易查詢',30),
 ('FUBON_API','FUBON_ETF_HOLDINGS_READ','ETF 成分股查詢',40),
 ('FUBON_API','FUBON_BANK_BALANCE_READ','交割銀行餘額',50),
 ('FUBON_API','FUBON_SETTLEMENT_READ','交割款查詢',60),
 ('FUBON_API','FUBON_REALIZED_GAINS_READ','已實現損益',70),
 ('FUBON_API','FUBON_TW_QUOTES_LIVE','盤中台股即時報價',80),
 ('FUBON_API','FUBON_TAIEX_INDEX_STREAM','加權指數串流',90),
 ('FUBON_API','FUBON_DIVIDENDS_READ','股利資料查詢',100),
 ('FUBON_API','FUBON_TECHNICAL_INDICATORS_READ','技術指標查詢',110),
 ('FUBON_API','FUBON_STOCK_BASIC_READ','個股基本資料查詢',120),
 ('FUBON_API','FUBON_INTRADAY_CANDLES_READ','分鐘 K 線查詢',130),
 ('FUBON_API','FUBON_STOCK_PUSH_SUBSCRIPTIONS','個股推播訂閱',140),
 ('FUBON_API','FUBON_STOCK_PUSH_STREAM','個股推播串流',150)
ON CONFLICT (source, operation_key) DO NOTHING;

CREATE OR REPLACE FUNCTION reject_api_error_log_operation_mutation() RETURNS trigger AS $$
BEGIN RAISE EXCEPTION 'api_error_log_operation is immutable'; END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS api_error_log_operation_immutable ON api_error_log_operation;
CREATE TRIGGER api_error_log_operation_immutable
    BEFORE UPDATE OR DELETE ON api_error_log_operation
    FOR EACH ROW EXECUTE FUNCTION reject_api_error_log_operation_mutation();

CREATE OR REPLACE FUNCTION guard_api_error_log_retention() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN RAISE EXCEPTION 'api_error_log is append-only'; END IF;
    IF OLD.occurred_at >= transaction_timestamp() - interval '30 days' THEN
        RAISE EXCEPTION 'api_error_log is within retention window';
    END IF;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS api_error_log_retention_guard ON api_error_log;
CREATE TRIGGER api_error_log_retention_guard
    BEFORE UPDATE OR DELETE ON api_error_log
    FOR EACH ROW EXECUTE FUNCTION guard_api_error_log_retention();
