--liquibase formatted sql

--changeset steven:v1.29.0-stock-style
-- Requirement 26：股票「成長型／收益型」風格細分（套在 asset_class=STOCK 之上的正交子維度）。
-- dividend_threshold 僅「收益型(INCOME)」列有值（殖利率門檻，可由設定頁調整，不寫死）。
CREATE TABLE IF NOT EXISTS stock_style (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code               VARCHAR(20)   NOT NULL UNIQUE,
    display_name       VARCHAR(50)   NOT NULL,
    sort_order         INTEGER       NOT NULL DEFAULT 0,
    active             BOOLEAN       NOT NULL DEFAULT TRUE,
    dividend_threshold DECIMAL(6,4)
);

INSERT INTO stock_style (code, display_name, sort_order, active, dividend_threshold) VALUES ('GROWTH', '成長型', 1, TRUE, NULL);
INSERT INTO stock_style (code, display_name, sort_order, active, dividend_threshold) VALUES ('INCOME', '收益型', 2, TRUE, 0.0400);

-- stock 主檔逐檔風格 override：非空覆蓋規則、null 依殖利率規則判定。
ALTER TABLE stock ADD COLUMN stock_style VARCHAR(20);
