--liquibase formatted sql

--changeset steven:v1.20.0-fund-dividend-history
--comment 信託基金配息歷史 + fund_holding 加 estimated_dividend 欄位 (Requirement 20)

CREATE TABLE fund_dividend_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fund_code   VARCHAR(20)    NOT NULL,
    base_date   DATE           NOT NULL,
    amount      NUMERIC(20,6)  NOT NULL,
    currency    VARCHAR(3),
    frequency   VARCHAR(20),
    fetched_at  TIMESTAMP      NOT NULL,
    CONSTRAINT uk_fund_div_code_date UNIQUE (fund_code, base_date)
);

CREATE INDEX idx_fund_div_code_date ON fund_dividend_history (fund_code, base_date DESC);

ALTER TABLE fund_holding ADD COLUMN estimated_dividend NUMERIC(20,2);
