--liquibase formatted sql

--changeset steven:v1.23.0-payment-category
CREATE TABLE IF NOT EXISTS payment_category (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(30)  NOT NULL UNIQUE,
    display_name VARCHAR(50)  NOT NULL,
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    active       BOOLEAN      NOT NULL DEFAULT TRUE
);

--changeset steven:v1.23.0-payment-account
CREATE TABLE IF NOT EXISTS payment_account (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id     BIGINT       NOT NULL REFERENCES payment_category(id),
    item_name       VARCHAR(100) NOT NULL,
    payment_account VARCHAR(100),
    note            VARCHAR(255),
    sort_order      INTEGER      NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_payment_account_category ON payment_account(category_id);
