--liquibase formatted sql

--changeset steven:v1.26.0-notification-recipient
-- 警示觸發 email 通知收件人；email 正規化（trim + toLowerCase）後寫入，DB 層 UNIQUE
CREATE TABLE IF NOT EXISTS notification_recipient (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL UNIQUE,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
