--liquibase formatted sql

--changeset steven:v1.28.0-asset-class
-- Requirement 25：現金／債券／股票 三分類。
-- asset_class：三分類的單一事實來源（取代寫死 enum），供圓餅圖第 4 tab 與「資產類別歸類」設定頁。
CREATE TABLE IF NOT EXISTS asset_class (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(20)  NOT NULL UNIQUE,
    display_name VARCHAR(50)  NOT NULL,
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    active       BOOLEAN      NOT NULL DEFAULT TRUE
);

INSERT INTO asset_class (code, display_name, sort_order, active) VALUES ('CASH',  '現金', 1, TRUE);
INSERT INTO asset_class (code, display_name, sort_order, active) VALUES ('BOND',  '債券', 2, TRUE);
INSERT INTO asset_class (code, display_name, sort_order, active) VALUES ('STOCK', '股票', 3, TRUE);

-- stock 主檔逐檔資產類別 override：非空覆蓋規則、null 依 AssetClassifier 規則自動判定。
ALTER TABLE stock ADD COLUMN asset_class VARCHAR(20);
