--liquibase formatted sql

--changeset steven:v1.33.0-stock-alert-recipient
-- 每條警示挑選通知收件人（Requirement 23 / Task 125）：警示 ↔ 收件人多對多 join 表。
-- ON DELETE CASCADE：刪除警示或收件人時自動清除對應 join 列（app 層亦會主動刪，雙保險）。
CREATE TABLE IF NOT EXISTS stock_alert_recipient (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id     BIGINT NOT NULL,
    recipient_id BIGINT NOT NULL,
    CONSTRAINT uq_stock_alert_recipient UNIQUE (alert_id, recipient_id),
    CONSTRAINT fk_sar_alert FOREIGN KEY (alert_id)
        REFERENCES stock_alert (id) ON DELETE CASCADE,
    CONSTRAINT fk_sar_recipient FOREIGN KEY (recipient_id)
        REFERENCES notification_recipient (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sar_alert ON stock_alert_recipient (alert_id);
CREATE INDEX IF NOT EXISTS idx_sar_recipient ON stock_alert_recipient (recipient_id);

-- 升級相容：把現有每條警示 × 現有每位收件人全配對回填，維持升級前「全部 active 收件人都收」的行為，
-- 不造成寄信回歸（升級後 dispatcher 改 per-alert 選定收件人）。
INSERT INTO stock_alert_recipient (alert_id, recipient_id)
SELECT a.id, r.id FROM stock_alert a CROSS JOIN notification_recipient r;
