--liquibase formatted sql

-- Requirement 28：Gmail OAuth2 登入與多租戶資料隔離。
-- 建立使用者主檔、先 seed 管理者，為「資產類」表加 owner_user_id 並把現有資料 backfill 給管理者，
-- 再加 NOT NULL + FK + index，最後把原本全域唯一的欄位改為每使用者唯一。

--changeset steven:v1.34.0-app-user
CREATE TABLE IF NOT EXISTS app_user (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL UNIQUE,
    name       VARCHAR(255),
    picture    VARCHAR(512),
    role       VARCHAR(20)  NOT NULL DEFAULT 'USER',     -- ADMIN / USER
    status     VARCHAR(20)  NOT NULL DEFAULT 'PENDING',  -- PENDING / ACTIVE / DISABLED
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--changeset steven:v1.34.0-seed-admin
-- 先 seed 管理者，使後續 backfill 有歸屬對象；登入流程走 upsert，不會重複建立。
INSERT INTO app_user (email, name, role, status)
VALUES ('tw.leader@gmail.com', '管理者', 'ADMIN', 'ACTIVE')
ON CONFLICT (email) DO NOTHING;

--changeset steven:v1.34.0-add-owner-columns
ALTER TABLE asset_snapshot         ADD COLUMN IF NOT EXISTS owner_user_id BIGINT;
ALTER TABLE realized_gain          ADD COLUMN IF NOT EXISTS owner_user_id BIGINT;
ALTER TABLE payment_account        ADD COLUMN IF NOT EXISTS owner_user_id BIGINT;
ALTER TABLE stock_alert            ADD COLUMN IF NOT EXISTS owner_user_id BIGINT;
ALTER TABLE notification_recipient ADD COLUMN IF NOT EXISTS owner_user_id BIGINT;

--changeset steven:v1.34.0-backfill-owner
-- 現有資料全歸管理者。
UPDATE asset_snapshot         SET owner_user_id = (SELECT id FROM app_user WHERE email = 'tw.leader@gmail.com') WHERE owner_user_id IS NULL;
UPDATE realized_gain          SET owner_user_id = (SELECT id FROM app_user WHERE email = 'tw.leader@gmail.com') WHERE owner_user_id IS NULL;
UPDATE payment_account        SET owner_user_id = (SELECT id FROM app_user WHERE email = 'tw.leader@gmail.com') WHERE owner_user_id IS NULL;
UPDATE stock_alert            SET owner_user_id = (SELECT id FROM app_user WHERE email = 'tw.leader@gmail.com') WHERE owner_user_id IS NULL;
UPDATE notification_recipient SET owner_user_id = (SELECT id FROM app_user WHERE email = 'tw.leader@gmail.com') WHERE owner_user_id IS NULL;

--changeset steven:v1.34.0-owner-not-null-fk-index
ALTER TABLE asset_snapshot         ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE realized_gain          ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE payment_account        ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE stock_alert            ALTER COLUMN owner_user_id SET NOT NULL;
ALTER TABLE notification_recipient ALTER COLUMN owner_user_id SET NOT NULL;

ALTER TABLE asset_snapshot         ADD CONSTRAINT fk_asset_snapshot_owner         FOREIGN KEY (owner_user_id) REFERENCES app_user (id);
ALTER TABLE realized_gain          ADD CONSTRAINT fk_realized_gain_owner          FOREIGN KEY (owner_user_id) REFERENCES app_user (id);
ALTER TABLE payment_account        ADD CONSTRAINT fk_payment_account_owner        FOREIGN KEY (owner_user_id) REFERENCES app_user (id);
ALTER TABLE stock_alert            ADD CONSTRAINT fk_stock_alert_owner            FOREIGN KEY (owner_user_id) REFERENCES app_user (id);
ALTER TABLE notification_recipient ADD CONSTRAINT fk_notification_recipient_owner FOREIGN KEY (owner_user_id) REFERENCES app_user (id);

CREATE INDEX IF NOT EXISTS idx_asset_snapshot_owner         ON asset_snapshot (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_realized_gain_owner          ON realized_gain (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_payment_account_owner        ON payment_account (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_stock_alert_owner            ON stock_alert (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_notification_recipient_owner ON notification_recipient (owner_user_id);

--changeset steven:v1.34.0-fix-unique-constraints
-- 原本全域唯一 → 每使用者唯一。inline UNIQUE 由 PostgreSQL 以 <table>_<column>_key 命名。
ALTER TABLE asset_snapshot DROP CONSTRAINT IF EXISTS asset_snapshot_snapshot_date_key;
ALTER TABLE asset_snapshot ADD CONSTRAINT uq_snapshot_owner_date UNIQUE (owner_user_id, snapshot_date);

ALTER TABLE notification_recipient DROP CONSTRAINT IF EXISTS notification_recipient_email_key;
ALTER TABLE notification_recipient ADD CONSTRAINT uq_recipient_owner_email UNIQUE (owner_user_id, email);
