--liquibase formatted sql

--changeset steven:v1.30.0-bond-term
-- Requirement 27：債券再細分「短期／中期／長期」（套在 asset_class=BOND 之上的子維度）。
CREATE TABLE IF NOT EXISTS bond_term (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(20)  NOT NULL UNIQUE,
    display_name VARCHAR(50)  NOT NULL,
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    active       BOOLEAN      NOT NULL DEFAULT TRUE
);

INSERT INTO bond_term (code, display_name, sort_order, active) VALUES ('SHORT', '短期', 1, TRUE);
INSERT INTO bond_term (code, display_name, sort_order, active) VALUES ('MID',   '中期', 2, TRUE);
INSERT INTO bond_term (code, display_name, sort_order, active) VALUES ('LONG',  '長期', 3, TRUE);

-- stock 主檔逐檔債券期別 override：非空覆蓋規則、null 依名稱規則判定。
ALTER TABLE stock ADD COLUMN bond_term VARCHAR(20);
