--liquibase formatted sql

--changeset steven:v1.57.0-market-analysis-send-time
--comment 今日股市分析（Requirement 31 / Task 191）可設定多個「分析寄送時間」：每個台股交易日於各啟用時間點各重跑一次分析並各寄一封。全域單一排程設定（不分租戶，比照 market_analysis_setting）。Seed 08:45＝Task 186 之原固定排程時點，保留現行行為。排程改每分鐘 tick 比對此表啟用時點。

CREATE TABLE market_analysis_send_time (
    id          BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    send_time   TIME      NOT NULL UNIQUE,   -- HH:mm（Asia/Taipei）分析寄送時點
    active      BOOLEAN   NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO market_analysis_send_time (send_time, active) VALUES ('08:45', TRUE);
