--liquibase formatted sql

--changeset steven:v1.60.0-commodity-price-history
--comment Requirement 40（Task 201）：公開資訊「油價金價」十年每日歷史。三個標的以 commodity_code 區分：WTI（西德州原油 CL=F，USD/桶）、BRENT（布蘭特原油 BZ=F，USD/桶）、GOLD（COMEX 黃金 GC=F，USD/盎司）。僅存原始收盤價 close_price；漲跌、漲跌幅、區間最高/最低/平均皆為衍生值，由前端與匯出時即時計算，不入庫（CLAUDE.md 禁止存衍生值）。無 owner_user_id：油金價為全域公開行情，比照 exchange_rate_history / stock_price_history，所有使用者共用同一份。(commodity_code, price_date) UNIQUE 供 upsert 覆寫同一日報價。本 changeset 寫成冪等（CREATE TABLE / INDEX IF NOT EXISTS），避免日後版號避讓改名導致 changeset id 變動、Liquibase 視為新 changeset 重跑時因表已存在而失敗。表內無 seed（資料由 external-materials-service 啟動回補十年後寫入），故毋須補償語句。
CREATE TABLE IF NOT EXISTS commodity_price_history (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commodity_code VARCHAR(20)   NOT NULL,
    price_date     DATE          NOT NULL,
    close_price    NUMERIC(12,4) NOT NULL,
    CONSTRAINT uq_commodity_price_code_date UNIQUE (commodity_code, price_date)
);

CREATE INDEX IF NOT EXISTS idx_commodity_price_code_date
    ON commodity_price_history (commodity_code, price_date);
