--liquibase formatted sql

--changeset steven:v1.63.0-trading-radar-notification
-- 每檔交易雷達狀態 Email 通知（Requirement 44 / Task 211）。
CREATE TABLE IF NOT EXISTS trading_radar_notification_setting (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id            BIGINT NOT NULL,
    stock_code               VARCHAR(20) NOT NULL,
    market                   VARCHAR(20) NOT NULL,
    active                   BOOLEAN NOT NULL DEFAULT TRUE,
    initialized              BOOLEAN NOT NULL DEFAULT FALSE,
    last_action              VARCHAR(50),
    last_counter_trend_state VARCHAR(50),
    created_at               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_trn_setting_owner_stock UNIQUE (owner_user_id, stock_code, market),
    CONSTRAINT fk_trn_setting_owner FOREIGN KEY (owner_user_id)
        REFERENCES app_user (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS trading_radar_notification_state (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_id   BIGINT NOT NULL,
    state_type   VARCHAR(30) NOT NULL,
    state_code   VARCHAR(50) NOT NULL,
    CONSTRAINT uq_trn_state UNIQUE (setting_id, state_type, state_code),
    CONSTRAINT ck_trn_state_type CHECK (state_type IN ('ACTION', 'COUNTER_TREND')),
    CONSTRAINT fk_trn_state_setting FOREIGN KEY (setting_id)
        REFERENCES trading_radar_notification_setting (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS trading_radar_notification_recipient (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_id   BIGINT NOT NULL,
    recipient_id BIGINT NOT NULL,
    CONSTRAINT uq_trn_recipient UNIQUE (setting_id, recipient_id),
    CONSTRAINT fk_trn_recipient_setting FOREIGN KEY (setting_id)
        REFERENCES trading_radar_notification_setting (id) ON DELETE CASCADE,
    CONSTRAINT fk_trn_recipient_recipient FOREIGN KEY (recipient_id)
        REFERENCES notification_recipient (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_trn_setting_stock
    ON trading_radar_notification_setting (stock_code, market, active);
CREATE INDEX IF NOT EXISTS idx_trn_state_setting
    ON trading_radar_notification_state (setting_id);
CREATE INDEX IF NOT EXISTS idx_trn_recipient_setting
    ON trading_radar_notification_recipient (setting_id);
CREATE INDEX IF NOT EXISTS idx_trn_recipient_recipient
    ON trading_radar_notification_recipient (recipient_id);
