--liquibase formatted sql

--changeset steven:v1.63.0-etf-nav-history
--comment Requirement 34（Task 211）：ETF 每日淨值與折溢價歷史。資料由 external-materials-service 每日抓取後寫入（台股＝證交所 MIS 全市場 ETF 彙整檔、美股＝Yahoo navPrice），Redis 只留最新一筆（TTL 96h）供即時匯出，此表負責長期留存以便日後回看折溢價走勢。無 owner_user_id：ETF 淨值為全域公開行情，比照 stock_price_history / commodity_price_history，所有使用者共用同一份。(stock_code, market, nav_date) UNIQUE 供 upsert 覆寫同一日（盤中多次抓取時後寫覆蓋前寫，故每日最終值＝當日最後一次抓到的值＝收盤後的值）。刻意不存「市價」欄：同一事實已在 stock_price_history.close_price，跨表重複儲存違反完整正規化。折溢價 premium_discount_pct 雖形式上可由市價與淨值推得，但**不是衍生值**：台股該值為證交所發布的權威數字，且其淨值欄在股票型 ETF 已四捨五入至小數 2 位，由淨值反推誤差達 0.07 個百分點、與證交所公告對不起來，故必須原樣保存來源值（此為刻意 denormalization，理由同 asset_snapshot 的歷史快照欄位）。本 changeset 寫成冪等（CREATE TABLE / INDEX IF NOT EXISTS），避免日後版號避讓改名導致 changeset id 變動、Liquibase 視為新 changeset 重跑時因表已存在而失敗。表內無 seed（資料由排程寫入），故毋須補償語句。
CREATE TABLE IF NOT EXISTS etf_nav_history (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_code           VARCHAR(20)   NOT NULL,
    market               VARCHAR(20)   NOT NULL,
    nav_date             DATE          NOT NULL,
    nav                  NUMERIC(15,4) NOT NULL,
    premium_discount_pct NUMERIC(8,4),
    source               VARCHAR(30),
    CONSTRAINT uq_etf_nav_code_market_date UNIQUE (stock_code, market, nav_date)
);

CREATE INDEX IF NOT EXISTS idx_etf_nav_code_date
    ON etf_nav_history (stock_code, market, nav_date);
