--liquibase formatted sql

--changeset steven:v1.78.0-stock-alert-group
-- Requirement 16 / Task 253：複合條件警示（單層 AND 群組）。
-- 一個 stock_alert_group 綁 2～5 條件，群組內條件在同一次評估中全部成立才觸發一次；
-- 成員仍是 stock_alert 的列（以 group_id 指回群組），group_id IS NULL 者即 Task 253 之前的獨立單一條件。
-- 刻意不設 logic_op 欄位：本任務只做 AND，單一值的欄位屬「可計算得出的衍生值」，違反本專案正規化原則；
-- 日後真要支援 OR 再加 nullable 欄位即可。
-- 冪等（IF NOT EXISTS）：全機共用一套運行中 DB、多 worktree 並行，本 changeset 可能已被別的分支套用；
-- 非冪等即 already exists → business-services crash loop 整站掛（Task 207 的教訓）。
CREATE TABLE IF NOT EXISTS stock_alert_group (
    id                      BIGSERIAL PRIMARY KEY,
    owner_user_id           BIGINT       NOT NULL REFERENCES app_user(id),
    stock_code              VARCHAR(20)  NOT NULL,
    market                  VARCHAR(20)  NOT NULL,
    active                  BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order           INTEGER      NOT NULL DEFAULT 0,
    last_triggered_at       TIMESTAMP,
    last_triggered_price    NUMERIC(16,4),
    last_triggered_ma_value NUMERIC(16,4),
    last_triggered_kd_value NUMERIC(10,4),
    last_triggered_d_value  NUMERIC(10,4),
    created_at              TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at              TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_sag_active      ON stock_alert_group(active);
CREATE INDEX IF NOT EXISTS idx_sag_code_market ON stock_alert_group(stock_code, market);
CREATE INDEX IF NOT EXISTS idx_sag_owner       ON stock_alert_group(owner_user_id);

-- 群組自己的收件人 join 表，比照既有 stock_alert_recipient（同樣不放 owner 欄位，
-- 租戶保護在寫入端以「只寫入 owner-filtered 白名單的交集」完成，見 Requirement 30 / Task 145）。
CREATE TABLE IF NOT EXISTS stock_alert_group_recipient (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id     BIGINT NOT NULL CONSTRAINT fk_sagr_group     REFERENCES stock_alert_group(id)     ON DELETE CASCADE,
    recipient_id BIGINT NOT NULL CONSTRAINT fk_sagr_recipient REFERENCES notification_recipient(id) ON DELETE CASCADE,
    CONSTRAINT uq_stock_alert_group_recipient UNIQUE (group_id, recipient_id)
);
CREATE INDEX IF NOT EXISTS idx_sagr_group     ON stock_alert_group_recipient(group_id);
CREATE INDEX IF NOT EXISTS idx_sagr_recipient ON stock_alert_group_recipient(recipient_id);

-- 刻意不設 DEFAULT：既有列全部保持 NULL ＝ 獨立單一條件，行為與 Task 253 之前完全相同，不做任何資料遷移。
ALTER TABLE stock_alert ADD COLUMN IF NOT EXISTS group_id BIGINT;
CREATE INDEX IF NOT EXISTS idx_stock_alert_group ON stock_alert(group_id);

-- 群組觸發只寫一筆 trigger（不是每個成員各寫一筆），否則補發路徑會把同一次 AND 觸發
-- 還原成 N 條獨立條件，文案與 live 寄出的合併 label 分歧；因此 alert_id 必須放寬為 nullable。
-- DROP NOT NULL 本身冪等：對已是 nullable 的欄位重複執行無作用。
ALTER TABLE stock_alert_trigger ADD COLUMN IF NOT EXISTS group_id BIGINT;
CREATE INDEX IF NOT EXISTS idx_sat_group ON stock_alert_trigger(group_id);
ALTER TABLE stock_alert_trigger ALTER COLUMN alert_id DROP NOT NULL;

--changeset steven:v1.78.0-stock-alert-group-constraints splitStatements:false
-- 具名 FK / CHECK 沒有 IF NOT EXISTS 語法，只能以 pg_constraint 存在性判斷達成冪等。
-- splitStatements:false 不可省：Liquibase 4.29.2 的 StringUtil.processMultiLineSQL 以 BEGIN / END
-- token 計數判斷是否身處區塊內，「END IF」的 END 會把計數減回 0，緊接的分號就被當成語句結尾切開
-- → dollar-quote 未閉合 → Postgres syntax error → migration 失敗 → business-services crash loop 整站掛。
-- 本 repo 既有含 DO 區塊的 changeset（v1.71.0 / v1.34.1）都帶這個旗標，無一例外。
-- ck_sat_alert_xor_group：alert_id 與 group_id 恰好一個非空 —— 獨立條件的觸發掛 alert_id、
-- 群組觸發掛 group_id；兩者皆空（孤兒列）或皆非空（歸屬矛盾）都會讓補發路徑無從還原 label。
-- 區塊內不寫 -- 註解，比照上述兩支既有檔案（Liquibase 的 stripComments 並非 dollar-quote aware）。
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_stock_alert_group') THEN
        ALTER TABLE stock_alert ADD CONSTRAINT fk_stock_alert_group
            FOREIGN KEY (group_id) REFERENCES stock_alert_group(id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_sat_group') THEN
        ALTER TABLE stock_alert_trigger ADD CONSTRAINT fk_sat_group
            FOREIGN KEY (group_id) REFERENCES stock_alert_group(id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_sat_alert_xor_group') THEN
        ALTER TABLE stock_alert_trigger ADD CONSTRAINT ck_sat_alert_xor_group
            CHECK ((alert_id IS NOT NULL) <> (group_id IS NOT NULL));
    END IF;
END $$;
