--liquibase formatted sql

--changeset steven:v1.8.0-transit-fund-type
CREATE TABLE IF NOT EXISTS transit_fund_type (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(30)  NOT NULL UNIQUE,
    display_name VARCHAR(50)  NOT NULL,
    payable      BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    active       BOOLEAN      NOT NULL DEFAULT TRUE
);
