--liquibase formatted sql

--changeset steven:v1.95.0-etf-nav-observation
--comment Requirement 65 / Task 309：ETF NAV/premium append-only observation。etf_nav_history 保留每日最新值相容用途；歷史 decision 僅讀本表並以 available_at 截斷，禁止把同日稍後覆寫的最終值洩漏到較早 signal。
CREATE TABLE IF NOT EXISTS etf_nav_observation (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_code           VARCHAR(20)   NOT NULL,
    market               VARCHAR(20)   NOT NULL,
    nav_date             DATE          NOT NULL,
    nav                  NUMERIC(15,4) NOT NULL,
    premium_discount_pct NUMERIC(8,4),
    pct_origin           VARCHAR(20),
    source               VARCHAR(64)   NOT NULL,
    observed_at          TIMESTAMPTZ   NOT NULL,
    available_at         TIMESTAMPTZ   NOT NULL,
    availability_basis   VARCHAR(48)   NOT NULL,
    CONSTRAINT ck_etf_nav_observation_available
        CHECK (available_at >= observed_at),
    CONSTRAINT uq_etf_nav_observation_identity
        UNIQUE (stock_code, market, nav_date, observed_at, source)
);

CREATE INDEX IF NOT EXISTS idx_etf_nav_observation_decision
    ON etf_nav_observation (stock_code, market, available_at, nav_date DESC);

CREATE INDEX IF NOT EXISTS idx_etf_nav_observation_nav_date
    ON etf_nav_observation (stock_code, market, nav_date, available_at DESC);
