--liquibase formatted sql

--changeset steven:v1.96.0-radar-market-observations
--comment Requirement 65 / Task 307.7：三大法人原始數值 append-only observation 與原物料來源／可得時間 provenance。新聞文字不得作為數值來源；舊原物料列保留 NULL timestamp，resolver 只能套用規格指定的保守重建邊界。
CREATE TABLE IF NOT EXISTS twse_institutional_daily (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trading_date         DATE,
    foreign_net          NUMERIC(20,2),
    trust_net            NUMERIC(20,2),
    dealer_net           NUMERIC(20,2),
    total_net            NUMERIC(20,2),
    provider             VARCHAR(64) NOT NULL,
    source_url           TEXT,
    observed_at          TIMESTAMPTZ NOT NULL,
    source_available_at  TIMESTAMPTZ,
    availability_basis   VARCHAR(64) NOT NULL,
    status               VARCHAR(20) NOT NULL,
    error_reason         TEXT,
    CONSTRAINT ck_twse_institutional_status
        CHECK (status IN ('AVAILABLE', 'UNAVAILABLE')),
    CONSTRAINT ck_twse_institutional_available_values
        CHECK (status <> 'AVAILABLE' OR (
            trading_date IS NOT NULL
            AND foreign_net IS NOT NULL
            AND trust_net IS NOT NULL
            AND dealer_net IS NOT NULL
            AND total_net IS NOT NULL
            AND source_url IS NOT NULL
        )),
    CONSTRAINT uq_twse_institutional_observation
        UNIQUE (provider, observed_at)
);

CREATE INDEX IF NOT EXISTS idx_twse_institutional_decision
    ON twse_institutional_daily (trading_date DESC, observed_at DESC);

ALTER TABLE commodity_price_history
    ADD COLUMN IF NOT EXISTS provider VARCHAR(64),
    ADD COLUMN IF NOT EXISTS source_url TEXT,
    ADD COLUMN IF NOT EXISTS source_available_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS fetched_at TIMESTAMPTZ;

ALTER TABLE commodity_price_history
    DROP CONSTRAINT IF EXISTS ck_commodity_source_time;

ALTER TABLE commodity_price_history
    ADD CONSTRAINT ck_commodity_source_time
        CHECK (source_available_at IS NULL OR fetched_at IS NULL
            OR source_available_at <= fetched_at);

CREATE INDEX IF NOT EXISTS idx_commodity_price_available
    ON commodity_price_history (commodity_code, source_available_at, price_date DESC);
