--liquibase formatted sql

--changeset steven:v1.92.0-treasury-yield-daily
--comment Requirement 58 / Task 275：不可拆分的美債殖利率 curve batch。complete 與 content_hash 是為 decision-time 單一 provider selection、immutable revision 與同內容 no-op 刻意保存的 batch snapshot metadata，不得拿來評分。全域公開行情，不帶 owner。

CREATE TABLE IF NOT EXISTS treasury_yield_batch (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curve_date         DATE NOT NULL,
    provider           VARCHAR(32) NOT NULL,
    source_url         TEXT NOT NULL,
    available_at       TIMESTAMPTZ NOT NULL,
    availability_basis VARCHAR(40) NOT NULL,
    fetched_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    complete           BOOLEAN NOT NULL,
    content_hash       VARCHAR(64) NOT NULL,
    CONSTRAINT uq_treasury_yield_batch_content UNIQUE (curve_date, provider, content_hash),
    CONSTRAINT ck_treasury_yield_batch_provider
        CHECK (provider IN ('US_TREASURY', 'YAHOO_PROXY')),
    CONSTRAINT ck_treasury_yield_batch_hash_length
        CHECK (CHAR_LENGTH(content_hash) = 64)
);

CREATE INDEX IF NOT EXISTS idx_treasury_yield_batch_decision
    ON treasury_yield_batch (complete, available_at, curve_date DESC);

CREATE TABLE IF NOT EXISTS treasury_yield_daily (
    batch_id      BIGINT NOT NULL REFERENCES treasury_yield_batch(id),
    tenor         VARCHAR(8) NOT NULL,
    yield_percent NUMERIC(10,4) NOT NULL,
    source_url    TEXT NOT NULL,
    PRIMARY KEY (batch_id, tenor),
    CONSTRAINT ck_treasury_yield_daily_tenor
        CHECK (tenor IN ('M3', 'Y5', 'Y10', 'Y30')),
    CONSTRAINT ck_treasury_yield_daily_value
        CHECK (yield_percent >= 0 AND yield_percent <= 100)
);
