--
-- 資產管理系統 — Schema-only 基準線（純結構、**不含任何資料**）
--
-- 用途
--   供程式碼審查與規格稽核比對「Entity / Liquibase changelog / 實際 DB」三者是否一致。
--   在此檔納入版控之前，真正的基準線 db/init/01_dump.sql 因含真實個人財務資料而被
--   .gitignore 排除（資安 Requirement 29），導致任何從 git 取得原始碼的人（CI／新進成員／
--   稽核）都無法查證欄位位數與 nullable，此類問題永遠無法被驗證或回歸測試。本檔即為
--   該基準線「去除資料」後的可版控鏡像。
--
-- ⚠ 本檔「不會」被執行
--   它刻意放在 db/ 而非 db/init/。docker-compose 只把 ./db/init 掛進
--   docker-entrypoint-initdb.d，故本檔不參與 DB 初始化，也不會與 01_dump.sql 衝突。
--   全新環境初始化／還原一律仍用 db/init/01_dump.sql（由部署方本機提供）。
--
-- 重新產生（schema 變更後請同步更新本檔）
--   docker exec asset-postgres pg_dump -U assets -d assets \
--     --schema-only --no-owner --no-privileges \
--     | grep -v '^\restrict\|^\unrestrict' > db/schema.sql
--   接著把本段標頭補回檔首。
--   註：pg_dump 16 會輸出帶「隨機 token」的 \restrict / \unrestrict 兩行，每次產生皆不同，
--       會造成無意義的 diff 雜訊，故上面刻意濾除；濾除後同一 schema 可位元級重現。
--
-- 產生資訊：PostgreSQL 16.14 / pg_dump 16.14，來源 asset-postgres 容器，2026-07-18
--

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255),
    picture character varying(512),
    role character varying(20) DEFAULT 'USER'::character varying NOT NULL,
    status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: asset_class; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.asset_class (
    id bigint NOT NULL,
    code character varying(20) NOT NULL,
    display_name character varying(50) NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--
-- Name: asset_class_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.asset_class ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asset_class_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: asset_snapshot; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.asset_snapshot (
    id bigint NOT NULL,
    estimated_annual_dividend numeric(20,2),
    notes character varying(500),
    realized_gain numeric(20,2),
    snapshot_date date NOT NULL,
    total_assets numeric(20,2),
    total_deposit numeric(20,2),
    total_fund_cost numeric(20,2),
    total_fund_value numeric(20,2),
    total_stock_cost numeric(20,2),
    total_stock_value numeric(20,2),
    usd_exchange_rate numeric(10,4),
    owner_user_id bigint NOT NULL
);


--
-- Name: asset_snapshot_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.asset_snapshot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asset_snapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: backup_record; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.backup_record (
    id bigint NOT NULL,
    folder character varying(20) NOT NULL,
    filename character varying(255) NOT NULL,
    size_bytes bigint DEFAULT 0 NOT NULL,
    modified_at timestamp without time zone NOT NULL,
    auto_pre_restore boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: backup_record_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.backup_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: backup_record_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.backup_record_id_seq OWNED BY public.backup_record.id;


--
-- Name: backup_setting; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.backup_setting (
    id integer DEFAULT 1 NOT NULL,
    manual_retention integer DEFAULT 5 NOT NULL,
    daily_retention integer DEFAULT 50 NOT NULL,
    weekly_retention integer DEFAULT 5 NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    backup_enabled boolean DEFAULT true NOT NULL,
    CONSTRAINT backup_setting_daily_range CHECK (((daily_retention >= 1) AND (daily_retention <= 999))),
    CONSTRAINT backup_setting_manual_range CHECK (((manual_retention >= 1) AND (manual_retention <= 999))),
    CONSTRAINT backup_setting_single_row CHECK ((id = 1)),
    CONSTRAINT backup_setting_weekly_range CHECK (((weekly_retention >= 1) AND (weekly_retention <= 999)))
);


--
-- Name: bank; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(50) NOT NULL,
    display_name character varying(50) NOT NULL,
    keywords character varying(200)
);


--
-- Name: bank_deposit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_deposit (
    id bigint NOT NULL,
    amount numeric(20,2) NOT NULL,
    currency character varying(20),
    deposit_type character varying(30) NOT NULL,
    notes character varying(200),
    original_amount numeric(20,4),
    snapshot_id bigint NOT NULL,
    bank_id bigint,
    annual_interest_rate numeric(7,4)
);


--
-- Name: bank_deposit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bank_deposit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_deposit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bank_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bank ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bond_term; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bond_term (
    id bigint NOT NULL,
    code character varying(20) NOT NULL,
    display_name character varying(50) NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--
-- Name: bond_term_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bond_term ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bond_term_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: broker; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.broker (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(50) NOT NULL,
    display_name character varying(50) NOT NULL,
    keywords character varying(200)
);


--
-- Name: broker_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.broker ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.broker_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: commodity_export_schedule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.commodity_export_schedule (
    id bigint NOT NULL,
    owner_user_id bigint NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    run_hour integer DEFAULT 8 NOT NULL,
    run_minute integer DEFAULT 0 NOT NULL,
    output_subpath character varying(255) DEFAULT 'input'::character varying NOT NULL,
    range_months integer,
    last_run_date date,
    last_run_at timestamp without time zone,
    last_run_status character varying(500),
    updated_at timestamp without time zone,
    CONSTRAINT ck_commodity_export_schedule_hour CHECK (((run_hour >= 0) AND (run_hour <= 23))),
    CONSTRAINT ck_commodity_export_schedule_minute CHECK (((run_minute >= 0) AND (run_minute <= 59))),
    CONSTRAINT ck_commodity_export_schedule_range CHECK (((range_months IS NULL) OR ((range_months >= 1) AND (range_months <= 120))))
);


--
-- Name: commodity_export_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.commodity_export_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: commodity_export_schedule_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.commodity_export_schedule_id_seq OWNED BY public.commodity_export_schedule.id;


--
-- Name: commodity_price_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.commodity_price_history (
    id bigint NOT NULL,
    commodity_code character varying(20) NOT NULL,
    price_date date NOT NULL,
    close_price numeric(12,4) NOT NULL
);


--
-- Name: commodity_price_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.commodity_price_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.commodity_price_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crawler_schedule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.crawler_schedule (
    id bigint NOT NULL,
    crawler_key character varying(64) NOT NULL,
    run_hour integer NOT NULL,
    run_minute integer NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    updated_at timestamp without time zone,
    CONSTRAINT ck_crawler_schedule_hour CHECK (((run_hour >= 0) AND (run_hour <= 23))),
    CONSTRAINT ck_crawler_schedule_minute CHECK (((run_minute >= 0) AND (run_minute <= 59)))
);


--
-- Name: crawler_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.crawler_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: crawler_schedule_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.crawler_schedule_id_seq OWNED BY public.crawler_schedule.id;


--
-- Name: daily_market_analysis; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_market_analysis (
    analysis_date date NOT NULL,
    bias character varying(16),
    confidence integer,
    summary text,
    key_factors text,
    news_highlights text,
    tw_context text,
    us_context text,
    model character varying(64),
    status character varying(16) NOT NULL,
    error_message text,
    raw_response text,
    generated_at timestamp with time zone NOT NULL,
    batch_id character varying(64),
    email_sent_at timestamp with time zone
);


--
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


--
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


--
-- Name: deposit_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.deposit_type (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(30) NOT NULL,
    display_name character varying(50) NOT NULL,
    sort_order integer NOT NULL
);


--
-- Name: deposit_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.deposit_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deposit_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exchange_rate_export_schedule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exchange_rate_export_schedule (
    id bigint NOT NULL,
    owner_user_id bigint NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    run_hour integer DEFAULT 8 NOT NULL,
    run_minute integer DEFAULT 0 NOT NULL,
    output_subpath character varying(255) DEFAULT 'input'::character varying NOT NULL,
    range_months integer,
    last_run_date date,
    last_run_at timestamp without time zone,
    last_run_status character varying(500),
    updated_at timestamp without time zone,
    CONSTRAINT ck_exchange_rate_export_schedule_hour CHECK (((run_hour >= 0) AND (run_hour <= 23))),
    CONSTRAINT ck_exchange_rate_export_schedule_minute CHECK (((run_minute >= 0) AND (run_minute <= 59))),
    CONSTRAINT ck_exchange_rate_export_schedule_range CHECK (((range_months IS NULL) OR ((range_months >= 1) AND (range_months <= 120))))
);


--
-- Name: exchange_rate_export_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.exchange_rate_export_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: exchange_rate_export_schedule_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.exchange_rate_export_schedule_id_seq OWNED BY public.exchange_rate_export_schedule.id;


--
-- Name: exchange_rate_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exchange_rate_history (
    id bigint NOT NULL,
    buy_rate numeric(10,4),
    currency character varying(10) NOT NULL,
    rate_date date NOT NULL,
    sell_rate numeric(10,4)
);


--
-- Name: exchange_rate_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exchange_rate_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exchange_rate_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: export_schedule_setting; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.export_schedule_setting (
    id bigint NOT NULL,
    owner_user_id bigint NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    run_hour integer DEFAULT 8 NOT NULL,
    run_minute integer DEFAULT 0 NOT NULL,
    output_subpath character varying(255) DEFAULT 'input'::character varying NOT NULL,
    last_run_date date,
    last_run_at timestamp without time zone,
    last_run_status character varying(500),
    updated_at timestamp without time zone,
    CONSTRAINT ck_export_schedule_hour CHECK (((run_hour >= 0) AND (run_hour <= 23))),
    CONSTRAINT ck_export_schedule_minute CHECK (((run_minute >= 0) AND (run_minute <= 59)))
);


--
-- Name: export_schedule_setting_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.export_schedule_setting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: export_schedule_setting_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.export_schedule_setting_id_seq OWNED BY public.export_schedule_setting.id;


--
-- Name: foreign_stock_daily_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.foreign_stock_daily_history (
    stock_code character varying(16) NOT NULL,
    trading_date date NOT NULL,
    close_point numeric(18,4) NOT NULL
);


--
-- Name: fund_class_override; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fund_class_override (
    fund_name character varying(150) NOT NULL,
    asset_class character varying(20),
    stock_style character varying(20),
    bond_term character varying(20)
);


--
-- Name: fund_dividend_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fund_dividend_history (
    id bigint NOT NULL,
    fund_code character varying(20) NOT NULL,
    base_date date NOT NULL,
    amount numeric(20,6) NOT NULL,
    currency character varying(3),
    frequency character varying(20),
    fetched_at timestamp without time zone NOT NULL
);


--
-- Name: fund_dividend_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fund_dividend_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fund_dividend_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fund_holding; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fund_holding (
    id bigint NOT NULL,
    current_value numeric(20,2) NOT NULL,
    fund_code character varying(20),
    fund_name character varying(100) NOT NULL,
    investment_amount numeric(20,2) NOT NULL,
    snapshot_id bigint NOT NULL,
    bank_id bigint,
    units numeric(20,4),
    estimated_dividend numeric(20,2)
);


--
-- Name: fund_holding_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fund_holding ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fund_holding_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fund_master; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fund_master (
    fund_code character varying(20) NOT NULL,
    fund_name character varying(150) NOT NULL,
    bank_id bigint,
    currency character varying(3) NOT NULL,
    site character varying(10) NOT NULL,
    fundclear_org_code character varying(20) NOT NULL,
    fundclear_fund_code character varying(20) NOT NULL,
    fundclear_class_code character varying(20) NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--
-- Name: fund_nav; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fund_nav (
    id bigint NOT NULL,
    fund_code character varying(20) NOT NULL,
    nav_date date NOT NULL,
    nav numeric(20,6) NOT NULL,
    source character varying(20) NOT NULL,
    fetched_at timestamp without time zone NOT NULL
);


--
-- Name: fund_nav_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fund_nav ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fund_nav_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: investment_planned_expense; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.investment_planned_expense (
    id bigint NOT NULL,
    owner_user_id bigint NOT NULL,
    expense_date date NOT NULL,
    name character varying(100),
    amount numeric(20,2) NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: investment_planned_expense_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.investment_planned_expense_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: investment_planned_expense_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.investment_planned_expense_id_seq OWNED BY public.investment_planned_expense.id;


--
-- Name: investment_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.investment_profile (
    id bigint NOT NULL,
    owner_user_id bigint NOT NULL,
    goals character varying(300),
    risk_tolerance character varying(20),
    expected_annual_return character varying(20),
    updated_at timestamp with time zone NOT NULL,
    retirement_date date,
    birth_date date,
    labor_insurance_monthly numeric(20,2),
    labor_insurance_start_date date,
    labor_pension_lump_sum numeric(20,2),
    labor_pension_claim_date date,
    assumed_annual_inflation_rate numeric(5,2),
    accumulation_annual_return_rate numeric(5,2),
    retirement_annual_return_rate numeric(5,2),
    retirement_annual_expense numeric(20,2),
    long_term_care_annual_expense numeric(20,2),
    long_term_care_start_age integer,
    pre_retirement_annual_salary numeric(20,2),
    pre_retirement_annual_expense numeric(20,2)
);


--
-- Name: investment_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.investment_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: investment_profile_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.investment_profile_id_seq OWNED BY public.investment_profile.id;


--
-- Name: japan_gdp_per_capita_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.japan_gdp_per_capita_history (
    year integer NOT NULL,
    gdp_usd numeric(12,2) NOT NULL,
    real_gdp_growth_rate numeric(8,4)
);


--
-- Name: korea_gdp_per_capita_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.korea_gdp_per_capita_history (
    year integer NOT NULL,
    gdp_usd numeric(12,2) NOT NULL,
    real_gdp_growth_rate numeric(8,4)
);


--
-- Name: market_analysis_send_time; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.market_analysis_send_time (
    id bigint NOT NULL,
    send_time time without time zone NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: market_analysis_send_time_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.market_analysis_send_time ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.market_analysis_send_time_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: market_analysis_setting; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.market_analysis_setting (
    id integer DEFAULT 1 NOT NULL,
    model character varying(64) DEFAULT 'claude-opus-4-8'::character varying NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    effort character varying(16) DEFAULT 'medium'::character varying NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    CONSTRAINT market_analysis_setting_single_row CHECK ((id = 1))
);


--
-- Name: market_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.market_type (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(20) NOT NULL,
    display_name character varying(50) NOT NULL,
    sort_order integer NOT NULL
);


--
-- Name: market_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.market_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.market_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news_headline; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.news_headline (
    id bigint NOT NULL,
    title character varying(500) NOT NULL,
    source character varying(100) NOT NULL,
    url character varying(1024) NOT NULL,
    category character varying(32) NOT NULL,
    region character varying(16),
    summary text,
    published_at timestamp with time zone NOT NULL,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    dedupe_key character varying(64) NOT NULL
);


--
-- Name: news_headline_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.news_headline_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: news_headline_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.news_headline_id_seq OWNED BY public.news_headline.id;


--
-- Name: notification_recipient; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_recipient (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    owner_user_id bigint NOT NULL,
    receive_market_analysis boolean DEFAULT true NOT NULL
);


--
-- Name: notification_recipient_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification_recipient ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_recipient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_account (
    id bigint NOT NULL,
    category_id bigint NOT NULL,
    item_name character varying(100) NOT NULL,
    payment_account character varying(100),
    note character varying(255),
    sort_order integer DEFAULT 0 NOT NULL,
    owner_user_id bigint NOT NULL
);


--
-- Name: payment_account_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment_account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_category (
    id bigint NOT NULL,
    code character varying(30) NOT NULL,
    display_name character varying(50) NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--
-- Name: payment_category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: portfolio_advice; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.portfolio_advice (
    id bigint NOT NULL,
    owner_user_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    model character varying(64),
    created_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    error_message character varying(1000),
    age integer,
    investment_horizon_years integer,
    monthly_investment numeric(20,2),
    goals character varying(300),
    risk_tolerance character varying(20),
    expected_annual_return character varying(20),
    based_on_snapshot_id bigint,
    based_on_snapshot_date date,
    based_on_total_assets numeric(20,2),
    raw_response text,
    result_json text
);


--
-- Name: portfolio_advice_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.portfolio_advice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: portfolio_advice_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.portfolio_advice_id_seq OWNED BY public.portfolio_advice.id;


--
-- Name: portfolio_advice_setting; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.portfolio_advice_setting (
    id integer NOT NULL,
    model character varying(64) NOT NULL,
    effort character varying(16) NOT NULL,
    web_search_max_uses integer NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: realized_gain; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.realized_gain (
    id bigint NOT NULL,
    asset_code character varying(20),
    asset_name character varying(50) NOT NULL,
    investment_cost numeric(20,2) NOT NULL,
    market character varying(20),
    proceeds numeric(20,2) NOT NULL,
    sale_price numeric(15,4),
    shares numeric(15,5),
    trade_date date NOT NULL,
    broker character varying(30),
    currency character varying(10),
    exchange_rate numeric(10,4),
    owner_user_id bigint NOT NULL,
    CONSTRAINT realized_gain_market_check CHECK (((market)::text = ANY (ARRAY[('台股'::character varying)::text, ('美股'::character varying)::text])))
);


--
-- Name: realized_gain_export_schedule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.realized_gain_export_schedule (
    id bigint NOT NULL,
    owner_user_id bigint NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    run_hour integer DEFAULT 8 NOT NULL,
    run_minute integer DEFAULT 0 NOT NULL,
    output_subpath character varying(255) DEFAULT 'input'::character varying NOT NULL,
    last_run_date date,
    last_run_at timestamp without time zone,
    last_run_status character varying(500),
    updated_at timestamp without time zone,
    CONSTRAINT ck_rg_export_schedule_hour CHECK (((run_hour >= 0) AND (run_hour <= 23))),
    CONSTRAINT ck_rg_export_schedule_minute CHECK (((run_minute >= 0) AND (run_minute <= 59)))
);


--
-- Name: realized_gain_export_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.realized_gain_export_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: realized_gain_export_schedule_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.realized_gain_export_schedule_id_seq OWNED BY public.realized_gain_export_schedule.id;


--
-- Name: realized_gain_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.realized_gain ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.realized_gain_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock (
    code character varying(20) NOT NULL,
    market character varying(20) NOT NULL,
    name character varying(100) NOT NULL,
    asset_class character varying(20),
    stock_style character varying(20),
    bond_term character varying(20)
);


--
-- Name: stock_alert; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_alert (
    id bigint NOT NULL,
    stock_code character varying(20) NOT NULL,
    market character varying(20) NOT NULL,
    alert_type character varying(50) NOT NULL,
    threshold numeric(10,4) NOT NULL,
    active boolean DEFAULT true NOT NULL,
    last_triggered_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    last_triggered_price numeric(16,4),
    last_triggered_kd_value numeric(10,4),
    last_triggered_ma_value numeric(16,4),
    last_triggered_d_value numeric(10,4),
    display_order integer DEFAULT 0 NOT NULL,
    ma_period integer,
    owner_user_id bigint NOT NULL
);


--
-- Name: stock_alert_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.stock_alert_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: stock_alert_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.stock_alert_id_seq OWNED BY public.stock_alert.id;


--
-- Name: stock_alert_recipient; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_alert_recipient (
    id bigint NOT NULL,
    alert_id bigint NOT NULL,
    recipient_id bigint NOT NULL
);


--
-- Name: stock_alert_recipient_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_alert_recipient ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_alert_recipient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_alert_trigger; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_alert_trigger (
    id bigint NOT NULL,
    alert_id bigint NOT NULL,
    stock_code character varying(20) NOT NULL,
    market character varying(20) NOT NULL,
    triggered_at timestamp without time zone NOT NULL,
    price numeric(10,4),
    monthly_ma numeric(10,4),
    quarterly_ma numeric(10,4),
    annual_ma numeric(10,4),
    k_value numeric(10,4),
    d_value numeric(10,4),
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: stock_alert_trigger_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.stock_alert_trigger_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: stock_alert_trigger_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.stock_alert_trigger_id_seq OWNED BY public.stock_alert_trigger.id;


--
-- Name: stock_dividend_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_dividend_history (
    id bigint NOT NULL,
    stock_code character varying(20) NOT NULL,
    market character varying(20) NOT NULL,
    year integer NOT NULL,
    cash_dividend numeric(15,6),
    stock_dividend numeric(15,6),
    ex_dividend_date date,
    yield_pct numeric(10,4),
    cash_payment_date date,
    stock_payment_date date,
    fill_days integer,
    previous_close numeric(15,4),
    source character varying(50),
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);

-- Task 292：基本面 observation history。相同期間可有多個 provider／修正版；
-- as-of 必須同時限制 source_available_at 與 observed_at，禁止覆寫舊 observation。
CREATE TABLE public.stock_valuation_daily (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_code character varying(20) NOT NULL,
    market character varying(20) NOT NULL,
    trading_date date NOT NULL,
    pe_ratio numeric(12,4),
    pb_ratio numeric(12,4),
    dividend_yield_pct numeric(12,4),
    pe_loss_flag boolean,
    provider character varying(20) NOT NULL,
    source_urls jsonb DEFAULT '[]'::jsonb NOT NULL,
    source_available_at timestamp with time zone NOT NULL,
    availability_basis character varying(20) NOT NULL,
    observed_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX idx_stock_valuation_asof ON public.stock_valuation_daily
    USING btree (stock_code, market, trading_date DESC, observed_at DESC);

CREATE TABLE public.stock_financial_quarter (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_code character varying(20) NOT NULL,
    market character varying(20) NOT NULL,
    fiscal_year integer NOT NULL,
    fiscal_quarter integer NOT NULL CHECK (fiscal_quarter BETWEEN 1 AND 4),
    eps numeric(12,4),
    net_income_parent bigint,
    equity_parent bigint,
    provider character varying(20) NOT NULL,
    source_urls jsonb DEFAULT '[]'::jsonb NOT NULL,
    source_available_at timestamp with time zone NOT NULL,
    availability_basis character varying(20) NOT NULL,
    observed_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX idx_stock_financial_asof ON public.stock_financial_quarter
    USING btree (stock_code, market, fiscal_year DESC, fiscal_quarter DESC, observed_at DESC);

CREATE TABLE public.stock_monthly_revenue (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_code character varying(20) NOT NULL,
    market character varying(20) NOT NULL,
    revenue_year integer NOT NULL,
    revenue_month integer NOT NULL CHECK (revenue_month BETWEEN 1 AND 12),
    industry_name character varying(100),
    revenue bigint,
    prior_year_revenue bigint,
    revenue_yoy_pct numeric(12,4),
    provider character varying(20) NOT NULL,
    source_urls jsonb DEFAULT '[]'::jsonb NOT NULL,
    source_available_at timestamp with time zone NOT NULL,
    availability_basis character varying(20) NOT NULL,
    observed_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX idx_stock_revenue_asof ON public.stock_monthly_revenue
    USING btree (stock_code, market, revenue_year DESC, revenue_month DESC, observed_at DESC);

CREATE TABLE public.industry_monthly_revenue (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    industry_name character varying(100) NOT NULL,
    revenue_year integer NOT NULL,
    revenue_month integer NOT NULL CHECK (revenue_month BETWEEN 1 AND 12),
    revenue numeric(24,0),
    prior_year_revenue numeric(24,0),
    revenue_yoy_pct numeric(12,4),
    company_count integer NOT NULL,
    provider character varying(20) NOT NULL,
    source_urls jsonb DEFAULT '[]'::jsonb NOT NULL,
    source_available_at timestamp with time zone NOT NULL,
    availability_basis character varying(20) NOT NULL,
    observed_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX idx_industry_revenue_asof ON public.industry_monthly_revenue
    USING btree (industry_name, revenue_year DESC, revenue_month DESC, observed_at DESC);


--
-- Name: stock_dividend_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.stock_dividend_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: stock_dividend_history_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.stock_dividend_history_id_seq OWNED BY public.stock_dividend_history.id;


--
-- Name: stock_holding; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_holding (
    id bigint NOT NULL,
    currency character varying(3),
    current_value numeric(20,2) NOT NULL,
    dividend_rate numeric(10,6),
    estimated_dividend numeric(20,4),
    investment_cost numeric(20,2) NOT NULL,
    market character varying(20) NOT NULL,
    original_currency_value numeric(20,4),
    shares numeric(15,5) NOT NULL,
    stock_code character varying(20) NOT NULL,
    snapshot_id bigint NOT NULL,
    broker_id bigint,
    transaction_type character varying(10),
    transaction_date date,
    transaction_exchange_rate numeric(10,4),
    display_order integer
);


--
-- Name: stock_holding_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_holding ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_holding_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_price_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_price_history (
    id bigint NOT NULL,
    close_price numeric(15,4) NOT NULL,
    high_price numeric(15,4),
    low_price numeric(15,4),
    market character varying(20) NOT NULL,
    open_price numeric(15,4),
    stock_code character varying(20) NOT NULL,
    trading_date date NOT NULL,
    volume bigint,
    close_source character varying(64)
);


--
-- Name: stock_price_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_price_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_price_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_style; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_style (
    id bigint NOT NULL,
    code character varying(20) NOT NULL,
    display_name character varying(50) NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    active boolean DEFAULT true NOT NULL,
    dividend_threshold numeric(6,4)
);


--
-- Name: stock_style_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_style ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_style_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: taiwan_gdp_per_capita_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.taiwan_gdp_per_capita_history (
    year integer NOT NULL,
    gdp_usd numeric(12,2) NOT NULL,
    real_gdp_growth_rate numeric(8,4)
);


--
-- Name: trading_calendar_export_schedule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trading_calendar_export_schedule (
    id bigint NOT NULL,
    owner_user_id bigint NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    run_hour integer DEFAULT 8 NOT NULL,
    run_minute integer DEFAULT 0 NOT NULL,
    format character varying(10) DEFAULT 'json'::character varying NOT NULL,
    output_subpath character varying(255) DEFAULT 'input'::character varying NOT NULL,
    last_run_date date,
    last_run_at timestamp without time zone,
    last_run_status character varying(500),
    updated_at timestamp without time zone,
    CONSTRAINT ck_tc_export_schedule_format CHECK (((format)::text = ANY ((ARRAY['json'::character varying, 'excel'::character varying])::text[]))),
    CONSTRAINT ck_tc_export_schedule_hour CHECK (((run_hour >= 0) AND (run_hour <= 23))),
    CONSTRAINT ck_tc_export_schedule_minute CHECK (((run_minute >= 0) AND (run_minute <= 59)))
);


--
-- Name: trading_calendar_export_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.trading_calendar_export_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: trading_calendar_export_schedule_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.trading_calendar_export_schedule_id_seq OWNED BY public.trading_calendar_export_schedule.id;


--
-- Name: transit_fund_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transit_fund_type (
    id bigint NOT NULL,
    code character varying(30) NOT NULL,
    display_name character varying(50) NOT NULL,
    payable boolean DEFAULT true NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--
-- Name: transit_fund_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transit_fund_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transit_fund_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tw_market_closure; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tw_market_closure (
    closure_date date NOT NULL,
    reason character varying(200) NOT NULL,
    source character varying(32) NOT NULL,
    raw_status character varying(500),
    detected_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: twse_index_daily_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.twse_index_daily_history (
    trading_date date NOT NULL,
    close_point numeric(12,2) NOT NULL,
    open_point numeric(12,2),
    high_point numeric(12,2),
    low_point numeric(12,2),
    close_point_tr numeric(12,2),
    trade_volume bigint,
    trade_value numeric(20,0)
);


--
-- Name: twse_index_year_end_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.twse_index_year_end_history (
    year integer NOT NULL,
    close_point numeric(12,2) NOT NULL
);


--
-- Name: us_index_daily_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.us_index_daily_history (
    index_code character varying(16) NOT NULL,
    trading_date date NOT NULL,
    open_point numeric(14,4),
    high_point numeric(14,4),
    low_point numeric(14,4),
    close_point numeric(14,4) NOT NULL
);


--
-- Name: backup_record id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.backup_record ALTER COLUMN id SET DEFAULT nextval('public.backup_record_id_seq'::regclass);


--
-- Name: commodity_export_schedule id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.commodity_export_schedule ALTER COLUMN id SET DEFAULT nextval('public.commodity_export_schedule_id_seq'::regclass);


--
-- Name: crawler_schedule id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.crawler_schedule ALTER COLUMN id SET DEFAULT nextval('public.crawler_schedule_id_seq'::regclass);


--
-- Name: exchange_rate_export_schedule id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exchange_rate_export_schedule ALTER COLUMN id SET DEFAULT nextval('public.exchange_rate_export_schedule_id_seq'::regclass);


--
-- Name: export_schedule_setting id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.export_schedule_setting ALTER COLUMN id SET DEFAULT nextval('public.export_schedule_setting_id_seq'::regclass);


--
-- Name: investment_planned_expense id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.investment_planned_expense ALTER COLUMN id SET DEFAULT nextval('public.investment_planned_expense_id_seq'::regclass);


--
-- Name: investment_profile id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.investment_profile ALTER COLUMN id SET DEFAULT nextval('public.investment_profile_id_seq'::regclass);


--
-- Name: news_headline id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_headline ALTER COLUMN id SET DEFAULT nextval('public.news_headline_id_seq'::regclass);


--
-- Name: portfolio_advice id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.portfolio_advice ALTER COLUMN id SET DEFAULT nextval('public.portfolio_advice_id_seq'::regclass);


--
-- Name: realized_gain_export_schedule id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realized_gain_export_schedule ALTER COLUMN id SET DEFAULT nextval('public.realized_gain_export_schedule_id_seq'::regclass);


--
-- Name: stock_alert id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_alert ALTER COLUMN id SET DEFAULT nextval('public.stock_alert_id_seq'::regclass);


--
-- Name: stock_alert_trigger id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_alert_trigger ALTER COLUMN id SET DEFAULT nextval('public.stock_alert_trigger_id_seq'::regclass);


--
-- Name: stock_dividend_history id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_dividend_history ALTER COLUMN id SET DEFAULT nextval('public.stock_dividend_history_id_seq'::regclass);


--
-- Name: trading_calendar_export_schedule id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trading_calendar_export_schedule ALTER COLUMN id SET DEFAULT nextval('public.trading_calendar_export_schedule_id_seq'::regclass);


--
-- Name: app_user app_user_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_email_key UNIQUE (email);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: asset_class asset_class_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asset_class
    ADD CONSTRAINT asset_class_code_key UNIQUE (code);


--
-- Name: asset_class asset_class_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asset_class
    ADD CONSTRAINT asset_class_pkey PRIMARY KEY (id);


--
-- Name: asset_snapshot asset_snapshot_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asset_snapshot
    ADD CONSTRAINT asset_snapshot_pkey PRIMARY KEY (id);


--
-- Name: backup_record backup_record_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.backup_record
    ADD CONSTRAINT backup_record_pkey PRIMARY KEY (id);


--
-- Name: backup_record backup_record_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.backup_record
    ADD CONSTRAINT backup_record_unique UNIQUE (folder, filename);


--
-- Name: backup_setting backup_setting_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.backup_setting
    ADD CONSTRAINT backup_setting_pkey PRIMARY KEY (id);


--
-- Name: bank_deposit bank_deposit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_deposit
    ADD CONSTRAINT bank_deposit_pkey PRIMARY KEY (id);


--
-- Name: bank bank_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank
    ADD CONSTRAINT bank_pkey PRIMARY KEY (id);


--
-- Name: bond_term bond_term_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bond_term
    ADD CONSTRAINT bond_term_code_key UNIQUE (code);


--
-- Name: bond_term bond_term_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bond_term
    ADD CONSTRAINT bond_term_pkey PRIMARY KEY (id);


--
-- Name: broker broker_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.broker
    ADD CONSTRAINT broker_pkey PRIMARY KEY (id);


--
-- Name: commodity_export_schedule commodity_export_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.commodity_export_schedule
    ADD CONSTRAINT commodity_export_schedule_pkey PRIMARY KEY (id);


--
-- Name: commodity_price_history commodity_price_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.commodity_price_history
    ADD CONSTRAINT commodity_price_history_pkey PRIMARY KEY (id);


--
-- Name: crawler_schedule crawler_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.crawler_schedule
    ADD CONSTRAINT crawler_schedule_pkey PRIMARY KEY (id);


--
-- Name: daily_market_analysis daily_market_analysis_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_market_analysis
    ADD CONSTRAINT daily_market_analysis_pkey PRIMARY KEY (analysis_date);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: deposit_type deposit_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposit_type
    ADD CONSTRAINT deposit_type_pkey PRIMARY KEY (id);


--
-- Name: exchange_rate_export_schedule exchange_rate_export_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exchange_rate_export_schedule
    ADD CONSTRAINT exchange_rate_export_schedule_pkey PRIMARY KEY (id);


--
-- Name: exchange_rate_history exchange_rate_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exchange_rate_history
    ADD CONSTRAINT exchange_rate_history_pkey PRIMARY KEY (id);


--
-- Name: export_schedule_setting export_schedule_setting_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.export_schedule_setting
    ADD CONSTRAINT export_schedule_setting_pkey PRIMARY KEY (id);


--
-- Name: foreign_stock_daily_history foreign_stock_daily_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.foreign_stock_daily_history
    ADD CONSTRAINT foreign_stock_daily_history_pkey PRIMARY KEY (stock_code, trading_date);


--
-- Name: fund_class_override fund_class_override_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_class_override
    ADD CONSTRAINT fund_class_override_pkey PRIMARY KEY (fund_name);


--
-- Name: fund_dividend_history fund_dividend_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_dividend_history
    ADD CONSTRAINT fund_dividend_history_pkey PRIMARY KEY (id);


--
-- Name: fund_holding fund_holding_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_holding
    ADD CONSTRAINT fund_holding_pkey PRIMARY KEY (id);


--
-- Name: fund_master fund_master_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_master
    ADD CONSTRAINT fund_master_pkey PRIMARY KEY (fund_code);


--
-- Name: fund_nav fund_nav_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_nav
    ADD CONSTRAINT fund_nav_pkey PRIMARY KEY (id);


--
-- Name: investment_planned_expense investment_planned_expense_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.investment_planned_expense
    ADD CONSTRAINT investment_planned_expense_pkey PRIMARY KEY (id);


--
-- Name: investment_profile investment_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.investment_profile
    ADD CONSTRAINT investment_profile_pkey PRIMARY KEY (id);


--
-- Name: japan_gdp_per_capita_history japan_gdp_per_capita_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.japan_gdp_per_capita_history
    ADD CONSTRAINT japan_gdp_per_capita_history_pkey PRIMARY KEY (year);


--
-- Name: korea_gdp_per_capita_history korea_gdp_per_capita_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.korea_gdp_per_capita_history
    ADD CONSTRAINT korea_gdp_per_capita_history_pkey PRIMARY KEY (year);


--
-- Name: market_analysis_send_time market_analysis_send_time_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_analysis_send_time
    ADD CONSTRAINT market_analysis_send_time_pkey PRIMARY KEY (id);


--
-- Name: market_analysis_send_time market_analysis_send_time_send_time_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_analysis_send_time
    ADD CONSTRAINT market_analysis_send_time_send_time_key UNIQUE (send_time);


--
-- Name: market_analysis_setting market_analysis_setting_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_analysis_setting
    ADD CONSTRAINT market_analysis_setting_pkey PRIMARY KEY (id);


--
-- Name: market_type market_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_type
    ADD CONSTRAINT market_type_pkey PRIMARY KEY (id);


--
-- Name: news_headline news_headline_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_headline
    ADD CONSTRAINT news_headline_pkey PRIMARY KEY (id);


--
-- Name: notification_recipient notification_recipient_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_recipient
    ADD CONSTRAINT notification_recipient_pkey PRIMARY KEY (id);


--
-- Name: payment_account payment_account_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_account
    ADD CONSTRAINT payment_account_pkey PRIMARY KEY (id);


--
-- Name: payment_category payment_category_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_category
    ADD CONSTRAINT payment_category_code_key UNIQUE (code);


--
-- Name: payment_category payment_category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_category
    ADD CONSTRAINT payment_category_pkey PRIMARY KEY (id);


--
-- Name: portfolio_advice portfolio_advice_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.portfolio_advice
    ADD CONSTRAINT portfolio_advice_pkey PRIMARY KEY (id);


--
-- Name: portfolio_advice_setting portfolio_advice_setting_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.portfolio_advice_setting
    ADD CONSTRAINT portfolio_advice_setting_pkey PRIMARY KEY (id);


--
-- Name: realized_gain_export_schedule realized_gain_export_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realized_gain_export_schedule
    ADD CONSTRAINT realized_gain_export_schedule_pkey PRIMARY KEY (id);


--
-- Name: realized_gain realized_gain_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realized_gain
    ADD CONSTRAINT realized_gain_pkey PRIMARY KEY (id);


--
-- Name: stock_alert stock_alert_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_alert
    ADD CONSTRAINT stock_alert_pkey PRIMARY KEY (id);


--
-- Name: stock_alert_recipient stock_alert_recipient_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_alert_recipient
    ADD CONSTRAINT stock_alert_recipient_pkey PRIMARY KEY (id);


--
-- Name: stock_alert_trigger stock_alert_trigger_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_alert_trigger
    ADD CONSTRAINT stock_alert_trigger_pkey PRIMARY KEY (id);


--
-- Name: stock_dividend_history stock_dividend_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_dividend_history
    ADD CONSTRAINT stock_dividend_history_pkey PRIMARY KEY (id);


--
-- Name: stock_holding stock_holding_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_holding
    ADD CONSTRAINT stock_holding_pkey PRIMARY KEY (id);


--
-- Name: stock stock_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock
    ADD CONSTRAINT stock_pkey PRIMARY KEY (code, market);


--
-- Name: stock_price_history stock_price_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_price_history
    ADD CONSTRAINT stock_price_history_pkey PRIMARY KEY (id);


--
-- Name: stock_style stock_style_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_style
    ADD CONSTRAINT stock_style_code_key UNIQUE (code);


--
-- Name: stock_style stock_style_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_style
    ADD CONSTRAINT stock_style_pkey PRIMARY KEY (id);


--
-- Name: taiwan_gdp_per_capita_history taiwan_gdp_per_capita_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.taiwan_gdp_per_capita_history
    ADD CONSTRAINT taiwan_gdp_per_capita_history_pkey PRIMARY KEY (year);


--
-- Name: trading_calendar_export_schedule trading_calendar_export_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trading_calendar_export_schedule
    ADD CONSTRAINT trading_calendar_export_schedule_pkey PRIMARY KEY (id);


--
-- Name: transit_fund_type transit_fund_type_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transit_fund_type
    ADD CONSTRAINT transit_fund_type_code_key UNIQUE (code);


--
-- Name: transit_fund_type transit_fund_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transit_fund_type
    ADD CONSTRAINT transit_fund_type_pkey PRIMARY KEY (id);


--
-- Name: tw_market_closure tw_market_closure_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tw_market_closure
    ADD CONSTRAINT tw_market_closure_pkey PRIMARY KEY (closure_date);


--
-- Name: twse_index_daily_history twse_index_daily_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.twse_index_daily_history
    ADD CONSTRAINT twse_index_daily_history_pkey PRIMARY KEY (trading_date);


--
-- Name: twse_index_year_end_history twse_index_year_end_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.twse_index_year_end_history
    ADD CONSTRAINT twse_index_year_end_history_pkey PRIMARY KEY (year);


--
-- Name: broker uk4kgt9prhx3clxdw9x0t4d3s01; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.broker
    ADD CONSTRAINT uk4kgt9prhx3clxdw9x0t4d3s01 UNIQUE (code);


--
-- Name: exchange_rate_history uk977p0we3c7unf4kuwcaefe2gb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exchange_rate_history
    ADD CONSTRAINT uk977p0we3c7unf4kuwcaefe2gb UNIQUE (currency, rate_date);


--
-- Name: fund_dividend_history uk_fund_div_code_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_dividend_history
    ADD CONSTRAINT uk_fund_div_code_date UNIQUE (fund_code, base_date);


--
-- Name: fund_nav uk_fund_nav_code_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_nav
    ADD CONSTRAINT uk_fund_nav_code_date UNIQUE (fund_code, nav_date);


--
-- Name: stock_price_history ukgoypknu8vhw2x3m63hpa7suxu; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_price_history
    ADD CONSTRAINT ukgoypknu8vhw2x3m63hpa7suxu UNIQUE (stock_code, market, trading_date);


--
-- Name: deposit_type ukj0oo653mssbv9x3d1n69oe7pb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposit_type
    ADD CONSTRAINT ukj0oo653mssbv9x3d1n69oe7pb UNIQUE (code);


--
-- Name: market_type ukmbg7rlqx90v5oya66p7e2emrs; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_type
    ADD CONSTRAINT ukmbg7rlqx90v5oya66p7e2emrs UNIQUE (code);


--
-- Name: bank uknc70mw7kj0k56c4pjpl6b0xwt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank
    ADD CONSTRAINT uknc70mw7kj0k56c4pjpl6b0xwt UNIQUE (code);


--
-- Name: commodity_export_schedule uq_commodity_export_schedule_owner; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.commodity_export_schedule
    ADD CONSTRAINT uq_commodity_export_schedule_owner UNIQUE (owner_user_id);


--
-- Name: commodity_price_history uq_commodity_price_code_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.commodity_price_history
    ADD CONSTRAINT uq_commodity_price_code_date UNIQUE (commodity_code, price_date);


--
-- Name: crawler_schedule uq_crawler_schedule_key_time; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.crawler_schedule
    ADD CONSTRAINT uq_crawler_schedule_key_time UNIQUE (crawler_key, run_hour, run_minute);


--
-- Name: exchange_rate_export_schedule uq_exchange_rate_export_schedule_owner; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exchange_rate_export_schedule
    ADD CONSTRAINT uq_exchange_rate_export_schedule_owner UNIQUE (owner_user_id);


--
-- Name: export_schedule_setting uq_export_schedule_owner; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.export_schedule_setting
    ADD CONSTRAINT uq_export_schedule_owner UNIQUE (owner_user_id);


--
-- Name: investment_profile uq_investment_profile_owner; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.investment_profile
    ADD CONSTRAINT uq_investment_profile_owner UNIQUE (owner_user_id);


--
-- Name: notification_recipient uq_recipient_owner_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_recipient
    ADD CONSTRAINT uq_recipient_owner_email UNIQUE (owner_user_id, email);


--
-- Name: realized_gain_export_schedule uq_rg_export_schedule_owner; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realized_gain_export_schedule
    ADD CONSTRAINT uq_rg_export_schedule_owner UNIQUE (owner_user_id);


--
-- Name: asset_snapshot uq_snapshot_owner_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asset_snapshot
    ADD CONSTRAINT uq_snapshot_owner_date UNIQUE (owner_user_id, snapshot_date);


--
-- Name: stock_alert_recipient uq_stock_alert_recipient; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_alert_recipient
    ADD CONSTRAINT uq_stock_alert_recipient UNIQUE (alert_id, recipient_id);


--
-- Name: trading_calendar_export_schedule uq_tc_export_schedule_owner; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trading_calendar_export_schedule
    ADD CONSTRAINT uq_tc_export_schedule_owner UNIQUE (owner_user_id);


--
-- Name: us_index_daily_history us_index_daily_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.us_index_daily_history
    ADD CONSTRAINT us_index_daily_history_pkey PRIMARY KEY (index_code, trading_date);


--
-- Name: idx_asset_snapshot_owner; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_asset_snapshot_owner ON public.asset_snapshot USING btree (owner_user_id);


--
-- Name: idx_backup_record_modified; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_backup_record_modified ON public.backup_record USING btree (modified_at DESC);


--
-- Name: idx_commodity_price_code_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_commodity_price_code_date ON public.commodity_price_history USING btree (commodity_code, price_date);


--
-- Name: idx_crawler_schedule_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_crawler_schedule_key ON public.crawler_schedule USING btree (crawler_key);


--
-- Name: idx_dividend_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dividend_lookup ON public.stock_dividend_history USING btree (stock_code, market, year DESC);


--
-- Name: idx_fund_div_code_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fund_div_code_date ON public.fund_dividend_history USING btree (fund_code, base_date DESC);


--
-- Name: idx_fund_nav_code_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fund_nav_code_date ON public.fund_nav USING btree (fund_code, nav_date DESC);


--
-- Name: idx_news_headline_cat; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_news_headline_cat ON public.news_headline USING btree (category, published_at DESC);


--
-- Name: idx_news_headline_recent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_news_headline_recent ON public.news_headline USING btree (published_at DESC);


--
-- Name: idx_notification_recipient_owner; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notification_recipient_owner ON public.notification_recipient USING btree (owner_user_id);


--
-- Name: idx_payment_account_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payment_account_category ON public.payment_account USING btree (category_id);


--
-- Name: idx_payment_account_owner; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payment_account_owner ON public.payment_account USING btree (owner_user_id);


--
-- Name: idx_planned_expense_owner; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_planned_expense_owner ON public.investment_planned_expense USING btree (owner_user_id, expense_date);


--
-- Name: idx_portfolio_advice_owner_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_portfolio_advice_owner_created ON public.portfolio_advice USING btree (owner_user_id, created_at DESC);


--
-- Name: idx_realized_gain_owner; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_realized_gain_owner ON public.realized_gain USING btree (owner_user_id);


--
-- Name: idx_sar_alert; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sar_alert ON public.stock_alert_recipient USING btree (alert_id);


--
-- Name: idx_sar_recipient; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sar_recipient ON public.stock_alert_recipient USING btree (recipient_id);


--
-- Name: idx_sph_code_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sph_code_date ON public.stock_price_history USING btree (stock_code, trading_date);


--
-- Name: idx_stock_alert_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stock_alert_active ON public.stock_alert USING btree (active);


--
-- Name: idx_stock_alert_code_market; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stock_alert_code_market ON public.stock_alert USING btree (stock_code, market);


--
-- Name: idx_stock_alert_owner; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stock_alert_owner ON public.stock_alert USING btree (owner_user_id);


--
-- Name: idx_stock_alert_trigger_alert_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stock_alert_trigger_alert_time ON public.stock_alert_trigger USING btree (alert_id, triggered_at DESC);


--
-- Name: idx_stock_alert_trigger_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stock_alert_trigger_created_at ON public.stock_alert_trigger USING btree (created_at);


--
-- Name: uk_dividend_event; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_dividend_event ON public.stock_dividend_history USING btree (stock_code, market, year, COALESCE(ex_dividend_date, '1970-01-01'::date));


--
-- Name: uk_news_headline_dedupe; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_news_headline_dedupe ON public.news_headline USING btree (dedupe_key);


--
-- Name: fund_holding fk2ic58t3gkyb93k5qiavdn43x6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_holding
    ADD CONSTRAINT fk2ic58t3gkyb93k5qiavdn43x6 FOREIGN KEY (snapshot_id) REFERENCES public.asset_snapshot(id);


--
-- Name: stock_holding fk7mnwqhx8fc8nk9c0i0te8ocxc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_holding
    ADD CONSTRAINT fk7mnwqhx8fc8nk9c0i0te8ocxc FOREIGN KEY (snapshot_id) REFERENCES public.asset_snapshot(id);


--
-- Name: asset_snapshot fk_asset_snapshot_owner; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asset_snapshot
    ADD CONSTRAINT fk_asset_snapshot_owner FOREIGN KEY (owner_user_id) REFERENCES public.app_user(id);


--
-- Name: notification_recipient fk_notification_recipient_owner; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_recipient
    ADD CONSTRAINT fk_notification_recipient_owner FOREIGN KEY (owner_user_id) REFERENCES public.app_user(id);


--
-- Name: payment_account fk_payment_account_owner; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_account
    ADD CONSTRAINT fk_payment_account_owner FOREIGN KEY (owner_user_id) REFERENCES public.app_user(id);


--
-- Name: realized_gain fk_realized_gain_owner; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realized_gain
    ADD CONSTRAINT fk_realized_gain_owner FOREIGN KEY (owner_user_id) REFERENCES public.app_user(id);


--
-- Name: stock_alert_recipient fk_sar_alert; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_alert_recipient
    ADD CONSTRAINT fk_sar_alert FOREIGN KEY (alert_id) REFERENCES public.stock_alert(id) ON DELETE CASCADE;


--
-- Name: stock_alert_recipient fk_sar_recipient; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_alert_recipient
    ADD CONSTRAINT fk_sar_recipient FOREIGN KEY (recipient_id) REFERENCES public.notification_recipient(id) ON DELETE CASCADE;


--
-- Name: stock_alert fk_stock_alert_owner; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_alert
    ADD CONSTRAINT fk_stock_alert_owner FOREIGN KEY (owner_user_id) REFERENCES public.app_user(id);


--
-- Name: bank_deposit fkgh3kqmvrffwjl3rj7vmb6qisn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_deposit
    ADD CONSTRAINT fkgh3kqmvrffwjl3rj7vmb6qisn FOREIGN KEY (bank_id) REFERENCES public.bank(id);


--
-- Name: bank_deposit fkjxcn193425e8y6bdobkkma5jo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_deposit
    ADD CONSTRAINT fkjxcn193425e8y6bdobkkma5jo FOREIGN KEY (snapshot_id) REFERENCES public.asset_snapshot(id);


--
-- Name: stock_holding fklyb4h3jgxxou8j1smvo6qq2mc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_holding
    ADD CONSTRAINT fklyb4h3jgxxou8j1smvo6qq2mc FOREIGN KEY (broker_id) REFERENCES public.broker(id);


--
-- Name: fund_holding fkq9964x3qa2cdcxgdbqpitmobd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_holding
    ADD CONSTRAINT fkq9964x3qa2cdcxgdbqpitmobd FOREIGN KEY (bank_id) REFERENCES public.bank(id);


--
-- Name: fund_master fund_master_bank_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_master
    ADD CONSTRAINT fund_master_bank_id_fkey FOREIGN KEY (bank_id) REFERENCES public.bank(id);


--
-- Name: payment_account payment_account_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_account
    ADD CONSTRAINT payment_account_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.payment_category(id);


--
-- Name: stock_alert_trigger stock_alert_trigger_alert_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_alert_trigger
    ADD CONSTRAINT stock_alert_trigger_alert_id_fkey FOREIGN KEY (alert_id) REFERENCES public.stock_alert(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--
