package com.steven.assets.integration.fubon;

public enum FubonOutcome {
    DISABLED,
    INVENTORY_SYNC_DISABLED,
    INVENTORY_SYNC_CAPACITY_CONFLICT,
    MISCONFIGURED,
    CALENDAR_UNKNOWN,
    ACCOUNTING_FAILED,
    RECONCILE_FAILED,
    QUOTE_FAILED,
    NO_OWNER,
    NO_TODAY_SNAPSHOT,
    BROKER_MISSING,
    DRY_RUN,
    SUCCESS,
    EMPTY_CLEARED,
    ROLLED_BACK
}
